(() => {
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  const CKEY='ambilightCustomAnimationsV1';
  const editor={topology:{left:0,top:0,right:0}, leds:[], frames:[], selected:0, duration:6, fps:12, loop:true, pingpong:false, title:'My animation',emoji:'✨',description:'',brush:'#168cff',brightness:100,radius:0,trail:0,easing:'smoothstep',playing:false,timer:null,previewStart:0};
  const rgb=h=>{h=(h||'#000000').replace('#','');return {r:parseInt(h.slice(0,2),16)||0,g:parseInt(h.slice(2,4),16)||0,b:parseInt(h.slice(4,6),16)||0}};
  const hex=c=>'#'+[c.r,c.g,c.b].map(v=>Math.max(0,Math.min(255,Math.round(v))).toString(16).padStart(2,'0')).join('');
  const mix=(a,b,t)=>({r:a.r+(b.r-a.r)*t,g:a.g+(b.g-a.g)*t,b:a.b+(b.b-a.b)*t});
  const ease=t=>editor.easing==='linear'?t:editor.easing==='ease-in'?t*t:editor.easing==='ease-out'?1-(1-t)*(1-t):t*t*(3-2*t);
  function blankPixels(){const o={};editor.leds.forEach(x=>o[x.id]='#000000');return o}
  function frame(time=0,pixels){return {id:crypto.randomUUID?.()||Math.random().toString(36).slice(2),time:Number(time),pixels:pixels?structuredClone(pixels):blankPixels()}}
  function rebuildLeds(){const t=editor.topology,arr=[];for(let i=0;i<t.left;i++)arr.push({id:`left:${i}`,side:'left',index:i,pos:t.left<2?0:i/(t.left-1)});for(let i=0;i<t.top;i++)arr.push({id:`top:${i}`,side:'top',index:i,pos:t.top<2?0:i/(t.top-1)});for(let i=0;i<t.right;i++)arr.push({id:`right:${i}`,side:'right',index:i,pos:t.right<2?0:i/(t.right-1)});editor.leds=arr;if(!editor.frames.length)editor.frames=[frame(0),frame(editor.duration)];editor.frames.forEach(f=>editor.leds.forEach(l=>{if(!f.pixels[l.id])f.pixels[l.id]='#000000'}));renderEditor()}
  function current(){return editor.frames[editor.selected]||editor.frames[0]}
  function inject(){const ambi=$('#view-ambilight');if(!ambi||$('#animationCreator'))return;const section=document.createElement('section');section.id='animationCreator';section.className='creator card';section.innerHTML=`
    <div class="card-head"><div><h3>🎬 Animation Creator</h3><p>Maak je eigen pixel-animatie voor iedere Ambilight LED. Teken keyframes en laat kleuren soepel rond de TV bewegen.</p></div><span class="badge protected">Pixel timeline</span></div>
    <div class="creator-meta"><label>Emoji<input id="creatorEmoji" maxlength="4" value="✨"></label><label>Titel<input id="creatorTitle" maxlength="60" value="My animation"></label><label class="wide">Beschrijving<input id="creatorDesc" maxlength="160" placeholder="Bijv. een blauw lichtpunt reist van linksonder via boven naar rechts"></label></div>
    <div class="creator-toolbar"><label>Kleur<input id="creatorColor" type="color" value="#168cff"></label><label>Helderheid <span id="creatorBrightVal">100%</span><input id="creatorBrightness" type="range" min="0" max="100" value="100"></label><label>Glow radius <span id="creatorRadiusVal">0</span><input id="creatorRadius" type="range" min="0" max="6" value="0"></label><label>Trail <span id="creatorTrailVal">0</span><input id="creatorTrail" type="range" min="0" max="8" value="0"></label><button id="creatorAllOff" class="btn ghost">Alles uit</button><button id="creatorFill" class="btn secondary">Vul alle LEDs</button></div>
    <div class="creator-stage-wrap"><div class="creator-stage" id="creatorStage"><div class="creator-screen"><b id="creatorScreenTitle">✨ My animation</b><small>Klik of sleep over de LED-punten</small></div></div><div class="creator-legend"><span><i class="on"></i>Aan</span><span><i></i>Uit</span><span id="creatorTopology">Topology laden…</span></div></div>
    <div class="timeline-head"><div><b>Timeline / keyframes</b><small>Klik een frame om het te bewerken. De bridge interpoleert tussen frames.</small></div><div class="timeline-settings"><label>Duur<input id="creatorDuration" type="number" min="0.2" max="300" step="0.1" value="6"> s</label><label>FPS<select id="creatorFps"><option>8</option><option selected>12</option><option>16</option><option>20</option><option>25</option></select></label><label>Easing<select id="creatorEasing"><option value="linear">Linear</option><option value="smoothstep" selected>Smooth</option><option value="ease-in">Ease in</option><option value="ease-out">Ease out</option></select></label><label class="check"><input id="creatorLoop" type="checkbox" checked> Loop</label><label class="check"><input id="creatorPingpong" type="checkbox"> Ping-pong</label></div></div>
    <div class="creator-gradient" id="creatorGradient"><div class="creator-playhead" id="creatorPlayhead"></div></div><div class="creator-frames" id="creatorFrames"></div>
    <div class="creator-actions"><button id="creatorAddFrame" class="btn primary">+ Keyframe</button><button id="creatorDuplicate" class="btn secondary">Dupliceer</button><button id="creatorDelete" class="btn danger-fill">Verwijder</button><button id="creatorPreview" class="btn ghost">▶ Preview in editor</button><button id="creatorSend" class="btn primary">▶ Afspelen op TV</button><button id="creatorStop" class="btn danger-fill">■ Stop TV</button><button id="creatorSave" class="btn secondary">Opslaan</button><select id="creatorLibrary"><option value="">Opgeslagen animaties…</option></select></div>
    <div class="creator-tip"><b>Voorbeeld dat jij beschreef</b><span>Zet frame 0 volledig uit en klik alleen linksonder blauw. Voeg daarna frames toe waarin dat blauwe punt steeds één of twee LEDs verder schuift: links omhoog → over de bovenkant → rechts omlaag. Met Glow radius 1–2 krijgt het punt een zachte staart terwijl alle andere LEDs zwart blijven.</span></div>`;ambi.append(section);bind();loadTopology();loadLibrary()}
  async function loadTopology(){try{if(!state?.current)return;const x=await api(`/api/ambilight/topology?deviceId=${encodeURIComponent(state.current.id)}`);editor.topology={left:+x.left||0,top:+x.top||0,right:+x.right||0};rebuildLeds()}catch(e){$('#creatorTopology').textContent='Topology niet beschikbaar'} }
  function ledPoint(l){const t=editor.topology,s=$('#creatorStage'),w=s.clientWidth||700,h=s.clientHeight||380,m=25;let x,y;if(l.side==='left'){x=m;y=h-m-l.pos*(h-2*m)}else if(l.side==='top'){x=m+l.pos*(w-2*m);y=m}else{x=w-m;y=m+l.pos*(h-2*m)}return {x,y}}
  function renderEditor(){const st=$('#creatorStage');if(!st)return;st.querySelectorAll('.creator-led').forEach(x=>x.remove());const f=current();editor.leds.forEach(l=>{const p=ledPoint(l),b=document.createElement('button');b.type='button';b.className='creator-led';b.dataset.id=l.id;b.title=`${l.side} LED ${l.index+1}`;b.style.left=`${p.x}px`;b.style.top=`${p.y}px`;const c=f?.pixels[l.id]||'#000000';b.style.background=c;b.classList.toggle('lit',c.toLowerCase()!=='#000000');st.append(b)});$('#creatorTopology').textContent=`${editor.topology.left} links • ${editor.topology.top} boven • ${editor.topology.right} rechts`;$('#creatorScreenTitle').textContent=`${editor.emoji} ${editor.title}`;renderFrames();renderGradient()}
  function paint(id){const f=current();if(!f)return;const idx=editor.leds.findIndex(x=>x.id===id);if(idx<0)return;const base=rgb(editor.brush),scale=editor.brightness/100;base.r*=scale;base.g*=scale;base.b*=scale;for(let d=-editor.radius;d<=editor.radius;d++){const j=idx+d;if(j<0||j>=editor.leds.length)continue;const fall=editor.radius?1-Math.abs(d)/(editor.radius+1):1;f.pixels[editor.leds[j].id]=hex({r:base.r*fall,g:base.g*fall,b:base.b*fall})}for(let d=1;d<=editor.trail;d++){const j=idx-d;if(j<0)break;const fall=(editor.trail-d+1)/(editor.trail+1)*.65;f.pixels[editor.leds[j].id]=hex({r:base.r*fall,g:base.g*fall,b:base.b*fall})}renderEditor()}
  function renderFrames(){const box=$('#creatorFrames');box.innerHTML='';editor.frames.sort((a,b)=>a.time-b.time);editor.selected=Math.min(editor.selected,editor.frames.length-1);editor.frames.forEach((f,i)=>{const b=document.createElement('button');b.type='button';b.className='creator-frame'+(i===editor.selected?' active':'');b.style.left=`${Math.max(0,Math.min(100,f.time/editor.duration*100))}%`;b.innerHTML=`<span>${f.time.toFixed(2)}s</span>`;b.onclick=()=>{editor.selected=i;renderEditor()};box.append(b)})}
  function renderGradient(){const bar=$('#creatorGradient');if(!bar)return;const stops=editor.frames.map(f=>{const vals=Object.values(f.pixels).map(rgb),n=vals.length||1,a=vals.reduce((q,c)=>({r:q.r+c.r,g:q.g+c.g,b:q.b+c.b}),{r:0,g:0,b:0});return `${hex({r:a.r/n,g:a.g/n,b:a.b/n})} ${f.time/editor.duration*100}%`});bar.style.background=stops.length>1?`linear-gradient(90deg,${stops.join(',')})`:'#111827'}
  function sample(t){const fs=editor.frames.slice().sort((a,b)=>a.time-b.time);if(t<=fs[0].time)return fs[0].pixels;if(t>=fs.at(-1).time)return fs.at(-1).pixels;let a=fs[0],b=fs[1];for(let i=0;i<fs.length-1;i++)if(t>=fs[i].time&&t<=fs[i+1].time){a=fs[i];b=fs[i+1];break}const k=ease((t-a.time)/Math.max(.001,b.time-a.time)),out={};editor.leds.forEach(l=>out[l.id]=hex(mix(rgb(a.pixels[l.id]),rgb(b.pixels[l.id]),k)));return out}
  function preview(){if(editor.playing){editor.playing=false;cancelAnimationFrame(editor.timer);$('#creatorPreview').textContent='▶ Preview in editor';return}editor.playing=true;editor.previewStart=performance.now();$('#creatorPreview').textContent='■ Stop preview';const loop=n=>{if(!editor.playing)return;let t=(n-editor.previewStart)/1000;if(editor.loop)t%=editor.duration;else if(t>editor.duration){editor.playing=false;$('#creatorPreview').textContent='▶ Preview in editor';return}const p=sample(t);$$('.creator-led').forEach(x=>{const c=p[x.dataset.id]||'#000';x.style.background=c;x.classList.toggle('lit',c!=='#000000')});$('#creatorPlayhead').style.left=`${t/editor.duration*100}%`;editor.timer=requestAnimationFrame(loop)};editor.timer=requestAnimationFrame(loop)}
  function serialize(){return {version:1,title:editor.title,emoji:editor.emoji,description:editor.description,duration:editor.duration,fps:editor.fps,loop:editor.loop,pingpong:editor.pingpong,easing:editor.easing,topology:editor.topology,frames:editor.frames}}
  async function send(){if(!state?.current)return toast('Connect eerst een TV');try{await api('/api/ambilight/custom/start',{method:'POST',body:JSON.stringify({deviceId:state.current.id,animation:serialize()})});toast(`${editor.emoji} ${editor.title} speelt nu op de TV`)}catch(e){toast(`Custom animation: ${controlError?controlError(e):e.message}`)}}
  async function stop(){if(!state?.current)return;try{await api('/api/ambilight/animation/stop',{method:'POST',body:JSON.stringify({deviceId:state.current.id})});toast('Animatie gestopt')}catch(e){toast(e.message)}}
  function saveLocal(){const all=JSON.parse(localStorage.getItem(CKEY)||'{}'),id=(editor.title||'animation').toLowerCase().replace(/[^a-z0-9]+/g,'-')+'-'+Date.now();all[id]=serialize();localStorage.setItem(CKEY,JSON.stringify(all));loadLibrary();toast('Animatie opgeslagen')}
  function loadLibrary(){const sel=$('#creatorLibrary');if(!sel)return;const all=JSON.parse(localStorage.getItem(CKEY)||'{}');sel.innerHTML='<option value="">Opgeslagen animaties…</option>';Object.entries(all).forEach(([id,a])=>{const o=document.createElement('option');o.value=id;o.textContent=`${a.emoji||'✨'} ${a.title}`;sel.append(o)});sel.onchange=()=>{const a=all[sel.value];if(!a)return;Object.assign(editor,a,{selected:0,playing:false});$('#creatorTitle').value=editor.title;$('#creatorEmoji').value=editor.emoji;$('#creatorDesc').value=editor.description||'';$('#creatorDuration').value=editor.duration;$('#creatorFps').value=editor.fps;$('#creatorEasing').value=editor.easing;$('#creatorLoop').checked=editor.loop;$('#creatorPingpong').checked=editor.pingpong;rebuildLeds()}}
  function bind(){let down=false;const st=$('#creatorStage');st.addEventListener('pointerdown',e=>{const l=e.target.closest('.creator-led');if(l){down=true;st.setPointerCapture?.(e.pointerId);paint(l.dataset.id)}});st.addEventListener('pointermove',e=>{if(!down)return;const el=document.elementFromPoint(e.clientX,e.clientY)?.closest('.creator-led');if(el)paint(el.dataset.id)});st.addEventListener('pointerup',()=>down=false);st.addEventListener('pointercancel',()=>down=false);
    $('#creatorColor').oninput=e=>editor.brush=e.target.value;$('#creatorBrightness').oninput=e=>{editor.brightness=+e.target.value;$('#creatorBrightVal').textContent=e.target.value+'%'};$('#creatorRadius').oninput=e=>{editor.radius=+e.target.value;$('#creatorRadiusVal').textContent=e.target.value};$('#creatorTrail').oninput=e=>{editor.trail=+e.target.value;$('#creatorTrailVal').textContent=e.target.value};$('#creatorTitle').oninput=e=>{editor.title=e.target.value;renderEditor()};$('#creatorEmoji').oninput=e=>{editor.emoji=e.target.value;renderEditor()};$('#creatorDesc').oninput=e=>editor.description=e.target.value;
    $('#creatorDuration').onchange=e=>{editor.duration=Math.max(.2,Math.min(300,+e.target.value||6));editor.frames.forEach(f=>f.time=Math.min(f.time,editor.duration));renderEditor()};$('#creatorFps').onchange=e=>editor.fps=+e.target.value;$('#creatorEasing').onchange=e=>editor.easing=e.target.value;$('#creatorLoop').onchange=e=>editor.loop=e.target.checked;$('#creatorPingpong').onchange=e=>editor.pingpong=e.target.checked;
    $('#creatorAllOff').onclick=()=>{current().pixels=blankPixels();renderEditor()};$('#creatorFill').onclick=()=>{const c=hex(Object.fromEntries(Object.entries(rgb(editor.brush)).map(([k,v])=>[k,v*editor.brightness/100])));editor.leds.forEach(l=>current().pixels[l.id]=c);renderEditor()};
    $('#creatorAddFrame').onclick=()=>{const t=Math.min(editor.duration,Math.max(0,current().time+.5));editor.frames.push(frame(t,current().pixels));editor.selected=editor.frames.length-1;renderEditor()};$('#creatorDuplicate').onclick=()=>{const f=current();editor.frames.push(frame(Math.min(editor.duration,f.time+.25),f.pixels));editor.selected=editor.frames.length-1;renderEditor()};$('#creatorDelete').onclick=()=>{if(editor.frames.length<=2)return toast('Minimaal 2 keyframes');editor.frames.splice(editor.selected,1);editor.selected=Math.max(0,editor.selected-1);renderEditor()};
    $('#creatorFrames').addEventListener('dblclick',e=>{const r=e.currentTarget.getBoundingClientRect(),t=Math.max(0,Math.min(editor.duration,(e.clientX-r.left)/r.width*editor.duration));editor.frames.push(frame(t,current().pixels));editor.selected=editor.frames.length-1;renderEditor()});
    $('#creatorPreview').onclick=preview;$('#creatorSend').onclick=send;$('#creatorStop').onclick=stop;$('#creatorSave').onclick=saveLocal;window.addEventListener('resize',renderEditor)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',inject);else inject();
})();