(() => {
 const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
 const positions={0:'Rechtsboven',1:'Linksboven',2:'Rechtsonder',3:'Linksonder',4:'Midden'};
 function inject(){if($('#view-announcements'))return;const style=document.createElement('style');style.textContent=`
 .announcement-grid{display:grid;grid-template-columns:1.05fr .95fr;gap:16px}.announcement-controls{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.announcement-controls .full{grid-column:1/-1}.announcement-preview{padding:22px;background:#080c13;border-radius:18px;min-height:360px;position:relative;overflow:hidden;border:1px solid var(--line)}.preview-tv{position:absolute;inset:20px;border:1px solid #ffffff18;border-radius:14px;background:radial-gradient(circle at 50% 30%,#18202c,#080b10 70%)}.osd{position:absolute;max-width:62%;min-width:220px;padding:15px 18px;border-radius:8px;box-shadow:0 18px 60px #0009;display:flex;gap:12px;align-items:flex-start;transition:.2s}.osd[data-pos="0"]{top:18px;right:18px}.osd[data-pos="1"]{top:18px;left:18px}.osd[data-pos="2"]{bottom:18px;right:18px}.osd[data-pos="3"]{bottom:18px;left:18px}.osd[data-pos="4"]{top:50%;left:50%;transform:translate(-50%,-50%)}.osd-copy{min-width:0}.osd-copy b,.osd-copy span{display:block;overflow-wrap:anywhere}.osd-copy span{margin-top:5px}.announcement-actions,.preset-row,.position-grid{display:flex;gap:8px;flex-wrap:wrap}.position-grid button.active,.preset-row button.active{outline:2px solid #6bb8ff}.color-row{display:grid;grid-template-columns:1fr 74px;gap:10px;align-items:end}.color-row input[type=color]{height:44px;width:100%;padding:3px}.range-line{display:flex;justify-content:space-between;gap:10px}.announcement-status-row{display:flex;justify-content:space-between;gap:10px;align-items:center}@media(max-width:900px){.announcement-grid,.announcement-controls{grid-template-columns:1fr}.announcement-controls .full{grid-column:auto}.announcement-preview{min-height:300px}.osd{max-width:78%}}
 `;document.head.append(style);
 const nav=$('.sidebar nav'),settings=nav?.querySelector('[data-view="settings"]');const n=document.createElement('button');n.className='nav';n.dataset.view='announcements';n.innerHTML='▰ <span>Announcements</span>';nav.insertBefore(n,settings||null);
 const v=document.createElement('section');v.className='view';v.id='view-announcements';v.innerHTML=`
 <div class="announcement-grid">
  <div class="card"><div class="card-head"><div><span class="eyebrow">REAL TV OVERLAY</span><h3>📺 Announcements Studio</h3><p>Alles hieronder wordt via PiPup rechtstreeks op je Philips TV getoond.</p></div><span id="pipupBadge" class="badge offline">Niet getest</span></div>
   <div class="preset-row full"><button class="btn ghost" data-preset="philips">Philips</button><button class="btn ghost" data-preset="info">Info blauw</button><button class="btn ghost" data-preset="warning">Waarschuwing</button><button class="btn ghost" data-preset="dark">Donker</button></div>
   <div class="announcement-controls" style="margin-top:14px">
    <label class="full">Titel<input id="announcementTitle" maxlength="80" value="PHILIPS TV"></label>
    <label class="full">Tekst<textarea id="announcementText" maxlength="500" style="min-height:120px">Film begint over 5 minuten!</textarea></label>
    <div><div class="range-line"><span>Zichtduur</span><b id="announcementDurationValue">5 sec</b></div><input id="announcementDuration" type="range" min="1" max="60" value="5"></div>
    <div><div class="range-line"><span>Titelgrootte</span><b id="titleSizeValue">20 px</b></div><input id="titleSize" type="range" min="8" max="40" value="20"></div>
    <div><div class="range-line"><span>Tekstgrootte</span><b id="messageSizeValue">14 px</b></div><input id="messageSize" type="range" min="8" max="40" value="14"></div>
    <div class="color-row"><label>Titelkleur<input id="titleColor" type="color" value="#ffffff"></label><label>Hex<input id="titleColorHex" value="#FFFFFF" maxlength="9"></label></div>
    <div class="color-row"><label>Tekstkleur<input id="messageColor" type="color" value="#ffffff"></label><label>Hex<input id="messageColorHex" value="#FFFFFF" maxlength="9"></label></div>
    <div class="color-row"><label>Achtergrond<input id="backgroundColor" type="color" value="#111820"></label><label>Alpha/hex<input id="backgroundColorHex" value="#CC111820" maxlength="9"></label></div>
    <div class="full"><b>Locatie op het scherm</b><div class="position-grid" style="margin-top:8px">${Object.entries(positions).map(([k,v])=>`<button class="btn ghost${k==='0'?' active':''}" data-position="${k}">${v}</button>`).join('')}</div></div>
   </div>
   <div class="announcement-actions" style="margin-top:16px"><button id="pipupTest" class="btn secondary">Test TV verbinding</button><button id="announcementSend" class="btn primary">▰ Stuur naar TV</button></div>
   <div id="announcementMessage" class="notice subtle" style="margin-top:12px">PiPup receiver klaar voor styling.</div>
  </div>
  <div class="card"><div class="card-head"><div><h3>Live TV preview</h3><p>Positie, kleuren en tekstgrootte worden direct nagebootst.</p></div><span id="positionLabel" class="badge protected">Rechtsboven</span></div><div class="announcement-preview"><div class="preview-tv"></div><div id="previewOsd" class="osd" data-pos="0"><div class="osd-copy"><b id="previewTitle">PHILIPS TV</b><span id="previewText">Film begint over 5 minuten!</span></div></div></div></div>
 </div>`;document.querySelector('main').append(v);bind();applyPreset('philips')}
 function open(){ $$('.view').forEach(x=>x.classList.toggle('active',x.id==='view-announcements'));$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view==='announcements'));$('#pageTitle').textContent='Announcements';$('#pageSub').textContent='Bouw en verstuur echte PiPup overlays naar je Philips TV.'}
 function deviceId(){return typeof state!=='undefined'&&state?.current?(state.current.id||(state.current.ip?`philips:${state.current.ip}`:null)):null}
 function message(t,type='subtle'){const x=$('#announcementMessage');x.className='notice '+type;x.textContent=t}
 function currentPosition(){return Number($('.position-grid button.active')?.dataset.position||0)}
 function hex8(hex,alpha='CC'){hex=String(hex||'').trim().toUpperCase();if(/^#[0-9A-F]{8}$/.test(hex))return hex;if(/^#[0-9A-F]{6}$/.test(hex))return '#'+alpha+hex.slice(1);return '#CC111820'}
 function syncPreview(){const osd=$('#previewOsd'),tc=$('#titleColorHex').value,mc=$('#messageColorHex').value,bg=$('#backgroundColorHex').value;$('#previewTitle').textContent=$('#announcementTitle').value||'PHILIPS TV';$('#previewText').textContent=$('#announcementText').value||'Typ een melding…';$('#previewTitle').style.color=tc;$('#previewText').style.color=mc;$('#previewTitle').style.fontSize=$('#titleSize').value+'px';$('#previewText').style.fontSize=$('#messageSize').value+'px';osd.style.background=bg;osd.dataset.pos=currentPosition();$('#positionLabel').textContent=positions[currentPosition()]||'Positie'}
 function applyPreset(name){const p={philips:{t:'#FFFFFF',m:'#FFFFFF',b:'#CC111820',ts:20,ms:14},info:{t:'#72B7FF',m:'#FFFFFF',b:'#DD0A1A2A',ts:22,ms:15},warning:{t:'#FFD45C',m:'#FFFFFF',b:'#DD2A1B08',ts:22,ms:15},dark:{t:'#FFFFFF',m:'#D8DDE5',b:'#EE080B10',ts:20,ms:14}}[name];if(!p)return;$('#titleColor').value=p.t;$('#titleColorHex').value=p.t;$('#messageColor').value=p.m;$('#messageColorHex').value=p.m;$('#backgroundColor').value='#'+p.b.slice(-6);$('#backgroundColorHex').value=p.b;$('#titleSize').value=p.ts;$('#messageSize').value=p.ms;$('#titleSizeValue').textContent=p.ts+' px';$('#messageSizeValue').textContent=p.ms+' px';$$('[data-preset]').forEach(b=>b.classList.toggle('active',b.dataset.preset===name));syncPreview()}
 async function test(){const b=$('#pipupTest');b.disabled=true;b.textContent='Testen…';try{const r=await api('/api/announcements/test',{method:'POST',body:JSON.stringify({deviceId:deviceId()})});$('#pipupBadge').textContent='TV receiver online';$('#pipupBadge').className='badge protected';message(`PiPup op ${r.ip}:7979 is bereikbaar. Testmelding verstuurd.`,'success')}catch(e){$('#pipupBadge').textContent='Receiver offline';$('#pipupBadge').className='badge offline';message('PiPup niet bereikbaar: '+e.message,'warning')}finally{b.disabled=false;b.textContent='Test TV verbinding'}}
 async function send(){const text=$('#announcementText').value.trim();if(!text)return message('Typ eerst een melding.','warning');const payload={deviceId:deviceId(),title:$('#announcementTitle').value.trim(),message:text,duration:Number($('#announcementDuration').value),position:currentPosition(),titleColor:$('#titleColorHex').value.toUpperCase(),messageColor:$('#messageColorHex').value.toUpperCase(),backgroundColor:$('#backgroundColorHex').value.toUpperCase(),titleSize:Number($('#titleSize').value),messageSize:Number($('#messageSize').value)};const b=$('#announcementSend');b.disabled=true;b.textContent='Versturen…';try{const r=await api('/api/announcements/send',{method:'POST',body:JSON.stringify(payload)});$('#pipupBadge').textContent='TV receiver online';$('#pipupBadge').className='badge protected';message(`Verstuurd naar ${r.ip} • ${positions[payload.position]} • ${payload.duration} sec.`,'success')}catch(e){message('Versturen mislukt: '+e.message,'warning')}finally{b.disabled=false;b.textContent='▰ Stuur naar TV'}}
 function bind(){document.querySelector('[data-view="announcements"]').onclick=open;['announcementTitle','announcementText'].forEach(id=>$('#'+id).oninput=syncPreview);$('#announcementDuration').oninput=e=>$('#announcementDurationValue').textContent=e.target.value+' sec';$('#titleSize').oninput=e=>{$('#titleSizeValue').textContent=e.target.value+' px';syncPreview()};$('#messageSize').oninput=e=>{$('#messageSizeValue').textContent=e.target.value+' px';syncPreview()};[['titleColor','titleColorHex'],['messageColor','messageColorHex']].forEach(([c,h])=>{$('#'+c).oninput=e=>{$('#'+h).value=e.target.value.toUpperCase();syncPreview()};$('#'+h).oninput=syncPreview});$('#backgroundColor').oninput=e=>{$('#backgroundColorHex').value=hex8(e.target.value);syncPreview()};$('#backgroundColorHex').oninput=syncPreview;$$('[data-position]').forEach(b=>b.onclick=()=>{$$('[data-position]').forEach(x=>x.classList.remove('active'));b.classList.add('active');syncPreview()});$$('[data-preset]').forEach(b=>b.onclick=()=>applyPreset(b.dataset.preset));$('#pipupTest').onclick=test;$('#announcementSend').onclick=send}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',inject);else inject();
})();