(() => {
 const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
 function inject(){if($('#view-announcements'))return;const style=document.createElement('style');style.textContent='.announcement-grid{display:grid;grid-template-columns:1.1fr .9fr;gap:16px}.announcement-preview{padding:32px;background:#080c13;border-radius:18px;min-height:190px;display:grid;place-items:start center}.osd{width:min(520px,100%);padding:16px 20px;border-radius:8px;background:rgba(25,29,36,.97);box-shadow:0 18px 60px #0008;display:flex;gap:13px;align-items:center}.osd i{width:32px;height:32px;border-radius:50%;background:#ffffff18;display:grid;place-items:center}.osd span{color:#d8dde5}.announcement-actions{display:flex;gap:10px;flex-wrap:wrap}@media(max-width:900px){.announcement-grid{grid-template-columns:1fr}}';document.head.append(style);
 const nav=$('.sidebar nav'),settings=nav?.querySelector('[data-view="settings"]');const n=document.createElement('button');n.className='nav';n.dataset.view='announcements';n.innerHTML='▰ <span>Announcements</span>';nav.insertBefore(n,settings||null);
 const v=document.createElement('section');v.className='view';v.id='view-announcements';v.innerHTML=`<div class="announcement-grid"><div class="card"><div class="card-head"><div><span class="eyebrow">REAL TV OVERLAY</span><h3>📺 Announcements</h3><p>Stuur vanuit dit panel een overlay naar PiPup op je Philips TV.</p></div><span id="pipupBadge" class="badge offline">Niet getest</span></div><label>Titel<input id="announcementTitle" maxlength="80" value="PHILIPS TV"></label><label>Tekst<textarea id="announcementText" maxlength="240" style="min-height:130px">Film begint over 5 minuten!</textarea></label><label>Zichtduur <b id="announcementDurationValue">5 seconden</b><input id="announcementDuration" type="range" min="1" max="60" value="5"></label><div class="announcement-actions"><button id="pipupTest" class="btn secondary">Test TV verbinding</button><button id="announcementSend" class="btn primary">▰ Stuur naar TV</button></div><div id="announcementMessage" class="notice subtle">PiPup moet op de TV geïnstalleerd zijn en netwerktoegang hebben.</div></div><div class="card"><div class="card-head"><div><h3>Preview</h3><p>Voorbeeld van de melding.</p></div></div><div class="announcement-preview"><div class="osd"><i>i</i><div><b id="previewTitle">PHILIPS TV</b><br><span id="previewText">Film begint over 5 minuten!</span></div></div></div></div></div>`;document.querySelector('main').append(v);bind()}
 function open(){ $$('.view').forEach(x=>x.classList.toggle('active',x.id==='view-announcements'));$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view==='announcements'));$('#pageTitle').textContent='Announcements';$('#pageSub').textContent='Stuur echte overlays naar je Philips TV via de lokale PiPup receiver.'}
 function deviceId(){return typeof state!=='undefined'&&state?.current?(state.current.id||(state.current.ip?`philips:${state.current.ip}`:null)):null}
 function message(t,type='subtle'){const x=$('#announcementMessage');x.className='notice '+type;x.textContent=t}
 async function test(){const b=$('#pipupTest');b.disabled=true;b.textContent='Testen…';try{const r=await api('/api/announcements/test',{method:'POST',body:JSON.stringify({deviceId:deviceId()})});$('#pipupBadge').textContent='TV receiver online';$('#pipupBadge').className='badge protected';message(`Verbonden met PiPup op ${r.ip}:7979. Er is een testmelding naar je TV gestuurd.`,'success')}catch(e){$('#pipupBadge').textContent='Receiver offline';$('#pipupBadge').className='badge offline';message('PiPup niet bereikbaar: '+e.message,'warning')}finally{b.disabled=false;b.textContent='Test TV verbinding'}}
 async function send(){const text=$('#announcementText').value.trim(),title=$('#announcementTitle').value.trim(),duration=Number($('#announcementDuration').value);if(!text)return message('Typ eerst een melding.','warning');const b=$('#announcementSend');b.disabled=true;b.textContent='Versturen…';try{const r=await api('/api/announcements/send',{method:'POST',body:JSON.stringify({deviceId:deviceId(),title,message:text,duration})});$('#pipupBadge').textContent='TV receiver online';$('#pipupBadge').className='badge protected';message(`Melding naar ${r.ip} gestuurd • ${duration} seconden zichtbaar.`,'success')}catch(e){message('Versturen mislukt: '+e.message,'warning')}finally{b.disabled=false;b.textContent='▰ Stuur naar TV'}}
 function bind(){document.querySelector('[data-view="announcements"]').onclick=open;$('#announcementText').oninput=e=>$('#previewText').textContent=e.target.value||'Typ een melding…';$('#announcementTitle').oninput=e=>$('#previewTitle').textContent=e.target.value||'PHILIPS TV';$('#announcementDuration').oninput=e=>$('#announcementDurationValue').textContent=`${e.target.value} seconden`;$('#pipupTest').onclick=test;$('#announcementSend').onclick=send}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',inject);else inject();
})();