const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const runningFromBridge=location.hostname==='localhost'||location.hostname==='127.0.0.1'||/^192\.168\.|^10\.|^172\.(1[6-9]|2\d|3[01])\./.test(location.hostname);
const defaultBridge=runningFromBridge?location.origin:'http://localhost:8765';
const state={bridgeUrl:localStorage.getItem('bridgeUrl')||defaultBridge,bridgeOnline:false,devices:JSON.parse(localStorage.getItem('devices')||'[]'),current:JSON.parse(localStorage.getItem('currentTv')||'null'),status:null};
const titles={home:['Home','Control every screen from one place.'],remote:['Remote','A full touch remote for your connected TV.'],apps:['Apps','Launch supported apps directly.'],ambilight:['Ambilight','Build the lighting you want.'],devices:['Devices','Discover, pair and manage TVs.'],settings:['Settings','Configure the bridge and local preferences.']};
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),3500)}
function vib(){if($('#haptics')?.checked&&navigator.vibrate)navigator.vibrate(18)}
function save(){localStorage.setItem('devices',JSON.stringify(state.devices));localStorage.setItem('currentTv',JSON.stringify(state.current));}
async function api(path,opts={}){const url=state.bridgeUrl.replace(/\/$/,'')+path;const ctrl=new AbortController();const timeout=setTimeout(()=>ctrl.abort(),12000);try{const r=await fetch(url,{...opts,headers:{'Content-Type':'application/json',...(opts.headers||{})},signal:ctrl.signal});const text=await r.text();let data={};try{data=text?JSON.parse(text):{}}catch{data={message:text}}if(!r.ok){const e=new Error(data.error||data.message||`HTTP ${r.status}`);e.data=data;throw e}return data}catch(e){if(e.name==='AbortError')throw new Error('Bridge timed out');throw e}finally{clearTimeout(timeout)}}
function bridgeUi(on,detail=''){state.bridgeOnline=on;$('#bridgeDot').classList.toggle('online',on);$('#bridgeStatus').textContent=on?'Bridge online':'Bridge offline';$('#bridgeUrlLabel').textContent=detail||state.bridgeUrl.replace(/^https?:\/\//,'');$('#statConnection').textContent=on?(state.current?'Connected':'Bridge ready'):'Offline';}
async function testBridge(silent=false){state.bridgeUrl=$('#bridgeUrl')?.value.trim()||state.bridgeUrl;try{const d=await api('/api/health');bridgeUi(true,`${(d.localIPv4s||[]).join(', ')||'localhost'} • v${d.version||'?'}`);if(!silent)toast(`Bridge online • scanning ${(d.subnets||[]).join(', ')||'local network'}`);return true}catch(e){bridgeUi(false,'Cannot reach localhost:8765');if(!silent)toast(`Bridge offline: ${e.message}. Open this app via http://localhost:8765`);return false}}
function go(view){$$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${view}`));$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===view));$('#pageTitle').textContent=titles[view][0];$('#pageSub').textContent=titles[view][1];if(view==='apps')loadApps();}
function deviceCard(d){const wrap=document.createElement('div');wrap.className='device-item';const info=document.createElement('div');const b=document.createElement('b');b.textContent=d.name||d.model||'Smart TV';const s=document.createElement('small');s.textContent=`${(d.brand||'TV').toUpperCase()} • ${d.ip||'Unknown IP'}${d.model?' • '+d.model:''}${d.api?' • '+d.api:''}`;info.append(b,s);const btn=document.createElement('button');btn.className='btn primary';btn.textContent=state.current?.id===d.id?'Connected':'Connect';btn.onclick=()=>connectTv(d);wrap.append(info,btn);return wrap}
function renderDevices(){const box=$('#savedDevices');box.innerHTML='';if(!state.devices.length){box.className='device-list empty';box.textContent='No saved TVs yet.'}else{box.className='device-list';state.devices.forEach(d=>box.append(deviceCard(d)))}updateCurrentUi()}
function updateCurrentUi(){const c=state.current;$('#heroTvName').textContent=c?.name||'No TV connected';$('#heroTvMeta').textContent=c?`${(c.brand||'TV').toUpperCase()} • ${c.model||'Smart TV'} • ${c.ip}`:'Start a network scan or add a TV manually.';$('#remoteDeviceName').textContent=c?.name||'No TV';$('#screenStatus').textContent=c?'CONNECTED':'OFFLINE';$('#statConnection').textContent=state.bridgeOnline?(c?'Connected':'Bridge ready'):'Offline';}
async function scan(){
  if(!(await testBridge(true))){toast('Bridge is not reachable. Start npm start, then open http://localhost:8765');return}
  const box=$('#scanResults');box.className='device-list';box.innerHTML='<div class="device-item"><div><b>Scanning your network…</b><small>SSDP + Philips JointSpace ports 1925/1926. Keep the TV powered on.</small></div></div>';
  try{
    const r=await api('/api/discover',{method:'POST',body:'{}'});box.innerHTML='';
    if(!r.devices?.length){box.className='device-list empty';box.innerHTML='No Philips TV found. Make sure PC and TV are on the same Wi-Fi/LAN and the TV is switched on. You can also enter its IP manually.';toast('Scan finished: no supported TV found');return}
    r.devices.forEach(d=>box.append(deviceCard(d)));toast(`${r.devices.length} TV${r.devices.length===1?'':'s'} found`)
  }catch(e){box.className='device-list empty';box.textContent=`Scan error: ${e.message}`;toast(`Scan failed: ${e.message}`)}
}
async function connectTv(d){
  if(!(await testBridge(true))){toast('Bridge is offline');return}
  try{const r=await api('/api/connect',{method:'POST',body:JSON.stringify(d)});const tv={...d,...r.device,id:r.device?.id||d.id||`${d.brand||'tv'}:${d.ip}`};state.current=tv;const i=state.devices.findIndex(x=>x.id===tv.id||x.ip===tv.ip);if(i>=0)state.devices[i]=tv;else state.devices.unshift(tv);save();renderDevices();await refreshStatus();toast(`Connected to ${tv.name||'TV'}`);go('home')}
  catch(e){if(e.data?.needsCredentials){toast('TV found! Philips pairing is required. Opening pairing page…');setTimeout(()=>location.href='./pair.html',900);return}toast(`Connect failed: ${e.message}`)}
}
async function key(k){vib();if(!state.current){toast('Connect a TV first');return}try{await api('/api/key',{method:'POST',body:JSON.stringify({deviceId:state.current.id,key:k})})}catch(e){toast(e.message)}}
async function refreshStatus(){if(!state.current||!state.bridgeOnline)return;try{const s=await api(`/api/status?deviceId=${encodeURIComponent(state.current.id)}`);state.status=s;$('#statVolume').textContent=Number.isFinite(s.volume)?s.volume:'—';$('#volumeValue').textContent=Number.isFinite(s.volume)?s.volume:'—';if(Number.isFinite(s.volume))$('#volumeSlider').value=s.volume;$('#statMute').textContent=s.muted===true?'Muted':s.muted===false?'Sound on':'Unknown';$('#statSource').textContent=s.source||s.app||'—';$('#statAmbilight').textContent=s.ambilight||'—'}catch{}}
async function setVolume(v){if(!state.current)return;$('#volumeValue').textContent=v;try{await api('/api/volume',{method:'POST',body:JSON.stringify({deviceId:state.current.id,volume:Number(v)})});$('#statVolume').textContent=v}catch(e){toast(e.message)}}
async function loadApps(){const box=$('#appsGrid');if(!state.current){box.className='apps-grid empty';box.textContent='Connect a TV to load apps.';return}box.className='apps-grid';box.innerHTML='Loading…';try{const r=await api(`/api/apps?deviceId=${encodeURIComponent(state.current.id)}`);box.innerHTML='';if(!r.apps?.length){box.className='apps-grid empty';box.textContent='This TV did not return installed apps.';return}r.apps.forEach(a=>{const b=document.createElement('button');b.className='app-tile';const icon=document.createElement('span');icon.className='app-icon';icon.textContent=(a.name||'?')[0].toUpperCase();const name=document.createElement('b');name.textContent=a.name;b.append(icon,name);b.onclick=async()=>{try{await api('/api/apps/launch',{method:'POST',body:JSON.stringify({deviceId:state.current.id,app:a})});toast(`Opening ${a.name}`)}catch(e){toast(e.message)}};box.append(b)})}catch(e){box.className='apps-grid empty';box.textContent=e.message}}
async function applyAmbilight(){if(!state.current){toast('Connect a TV first');return}const payload={deviceId:state.current.id,mode:$('#ambiMode').value,brightness:Number($('#ambiBrightness').value),color:$('#ambiColor').value};try{await api('/api/ambilight',{method:'POST',body:JSON.stringify(payload)});toast('Ambilight updated');refreshStatus()}catch(e){toast(e.message)}}
function manualAdd(){const ip=$('#manualIp').value.trim(),name=$('#manualName').value.trim()||'Philips TV',brand=$('#manualBrand').value;if(!/^\d{1,3}(\.\d{1,3}){3}$/.test(ip)){toast('Enter a valid local IPv4 address');return}connectTv({id:`${brand}:${ip}`,ip,name,brand})}
$$('.nav').forEach(b=>b.onclick=()=>go(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$$('[data-key]').forEach(b=>b.onclick=()=>key(b.dataset.key));
$('#scanBtn').onclick=scan;$('#deviceScanBtn').onclick=scan;$('#connectBtn').onclick=()=>testBridge();$('#manualAddBtn').onclick=manualAdd;$('#refreshAppsBtn').onclick=loadApps;$('#applyAmbiBtn').onclick=applyAmbilight;
$('#saveBridgeBtn').onclick=()=>{state.bridgeUrl=$('#bridgeUrl').value.trim().replace(/\/$/,'');localStorage.setItem('bridgeUrl',state.bridgeUrl);testBridge()};
$('#clearDataBtn').onclick=()=>{localStorage.clear();location.reload()};
let volumeTimer;$('#volumeSlider').oninput=e=>{clearTimeout(volumeTimer);$('#volumeValue').textContent=e.target.value;volumeTimer=setTimeout(()=>setVolume(e.target.value),180)};
$('#sendTextBtn').onclick=async()=>{const text=$('#textInput').value;if(!text||!state.current)return;try{await api('/api/text',{method:'POST',body:JSON.stringify({deviceId:state.current.id,text})});toast('Text sent')}catch(e){toast(e.message)}};
for(let n=1;n<=9;n++){const b=document.createElement('button');b.textContent=n;b.onclick=()=>key(`Digit${n}`);$('#channelGrid').append(b)};['0','CH +','CH −'].forEach((x,i)=>{const b=document.createElement('button');b.textContent=x;b.onclick=()=>key(i===0?'Digit0':i===1?'ChannelStepUp':'ChannelStepDown');$('#channelGrid').append(b)});
$('#bridgeUrl').value=state.bridgeUrl;renderDevices();testBridge(true).then(ok=>{if(ok&&state.current)refreshStatus()});if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});setInterval(()=>{if(state.bridgeOnline&&state.current)refreshStatus()},12000);
