const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const runningFromBridge=location.hostname==='localhost'||location.hostname==='127.0.0.1'||/^192\.168\.|^10\.|^172\.(1[6-9]|2\d|3[01])\./.test(location.hostname);
const defaultBridge=runningFromBridge?location.origin:'http://localhost:8765';
const state={bridgeUrl:localStorage.getItem('bridgeUrl')||defaultBridge,bridgeOnline:false,devices:JSON.parse(localStorage.getItem('devices')||'[]'),current:JSON.parse(localStorage.getItem('currentTv')||'null'),status:null,ambiInfo:null,zones:{left:true,top:true,right:true}};
const titles={home:['Home','Control and inspect your Philips TV without losing the saved connection.'],remote:['Remote','Philips remote control with secure-control detection.'],apps:['Apps','Application support reported by your firmware.'],ambilight:['Ambilight','Full Philips Ambilight modes, sub-modes and zones.'],android:['Android TV','Live Android/JointSpace features without another pairing flow.'],info:['TV info','Live TV details and connection protection.'],devices:['Devices','Discover or reconnect without re-pairing.'],settings:['Settings','Configure the local bridge and controller.']};
const fallbackPresets={FOLLOW_VIDEO:['STANDARD','VIVID','IMMERSIVE','NATURAL','GAME','COMFORT','RELAX'],FOLLOW_AUDIO:['ENERGY_ADAPTIVE_BRIGHTNESS','ENERGY_ADAPTIVE_COLORS','VU_METER','SPECTRUM_ANALYZER','KNIGHT_RIDER_CLOCKWISE','KNIGHT_RIDER_ALTERNATING','RANDOM_PIXEL_FLASH','STROBO','PARTY'],FOLLOW_COLOR:['CUSTOM_COLOR','HOT_LAVA','DEEP_WATER','FRESH_NATURE','WARM_WHITE','COOL_WHITE'],FLAG:['NETHERLANDS','BELGIUM','GERMANY','FRANCE','ITALY','SPAIN','UNITED_KINGDOM','EUROPE']};
function toast(msg){const t=$('#toast');if(!t)return;t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),5200)}
function vib(){if($('#haptics')?.checked&&navigator.vibrate)navigator.vibrate(16)}
function save(){localStorage.setItem('devices',JSON.stringify(state.devices));localStorage.setItem('currentTv',JSON.stringify(state.current))}
async function api(path,opts={}){const url=state.bridgeUrl.replace(/\/$/,'')+path,ctrl=new AbortController(),timeout=setTimeout(()=>ctrl.abort(),17000);try{const r=await fetch(url,{...opts,headers:{'Content-Type':'application/json',...(opts.headers||{})},signal:ctrl.signal});const text=await r.text();let data={};try{data=text?JSON.parse(text):{}}catch{data={message:text}}if(!r.ok){const e=new Error(data.error||data.message||`HTTP ${r.status}`);e.data=data;e.status=r.status;throw e}return data}catch(e){if(e.name==='AbortError')throw new Error('Bridge timed out');throw e}finally{clearTimeout(timeout)}}
function bridgeUi(on,detail=''){state.bridgeOnline=on;$('#bridgeDot')?.classList.toggle('online',on);$('#bridgeStatus')&&($('#bridgeStatus').textContent=on?'Bridge online':'Bridge offline');$('#bridgeUrlLabel')&&($('#bridgeUrlLabel').textContent=detail||state.bridgeUrl.replace(/^https?:\/\//,''));$('#statConnection')&&($('#statConnection').textContent=on?(state.current?'Connected':'Bridge ready'):'Offline')}
async function testBridge(silent=false){state.bridgeUrl=$('#bridgeUrl')?.value.trim()||state.bridgeUrl;try{const d=await api('/api/health');bridgeUi(true,`${(d.localIPv4s||[]).join(', ')||'localhost'} • v${d.version||'?'}`);if(!silent)toast(`Bridge online • v${d.version}`);return true}catch(e){bridgeUi(false,'localhost:8765 unavailable');if(!silent)toast(`Bridge offline: ${e.message}`);return false}}
function go(view){$$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${view}`));$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===view));$('#pageTitle').textContent=titles[view][0];$('#pageSub').textContent=titles[view][1];if(view==='apps')loadApps();if(view==='info')loadInfo();if(view==='ambilight')loadAmbilightInfo();if(view==='android')loadAndroidInfo();if(view==='remote')updateRemoteNotice()}
function deviceCard(d){const wrap=document.createElement('div');wrap.className='device-item';const info=document.createElement('div'),b=document.createElement('b'),s=document.createElement('small');b.textContent=d.name||d.model||'Philips TV';s.textContent=`PHILIPS • ${d.ip||'Unknown IP'}${d.apiVersion?' • API '+d.apiVersion:''}`;info.append(b,s);const btn=document.createElement('button');btn.className='btn '+(state.current?.ip===d.ip?'secondary':'primary');btn.textContent=state.current?.ip===d.ip?'Connected':'Connect';btn.onclick=()=>connectTv(d);wrap.append(info,btn);return wrap}
function renderDevices(){const box=$('#savedDevices');if(!box)return;box.innerHTML='';if(!state.devices.length){box.className='device-list empty';box.textContent='No saved TVs yet.'}else{box.className='device-list';state.devices.forEach(d=>box.append(deviceCard(d)))}updateCurrentUi()}
function updateCurrentUi(){const c=state.current;$('#heroTvName')&&($('#heroTvName').textContent=c?.name||'No TV connected');$('#heroTvMeta')&&($('#heroTvMeta').textContent=c?`Philips • ${c.model||'Smart TV'} • ${c.ip} • connection preserved`:'Your saved TV stays selected even when a single feature is unavailable.');$('#remoteDeviceName')&&($('#remoteDeviceName').textContent=c?.name||'No TV');$('#screenStatus')&&($('#screenStatus').textContent=c?'CONNECTED':'OFFLINE');const badge=$('#connectionBadge');if(badge){badge.textContent=c?'Connected':'Offline';badge.className=`badge ${c?'online':'offline'}`}}
async function scan(){if(!(await testBridge(true)))return toast('Bridge is not reachable');const box=$('#scanResults');box.className='device-list';box.innerHTML='<div class="device-item"><div><b>Scanning network…</b><small>Saved TVs first, then LAN discovery.</small></div></div>';try{const r=await api('/api/discover',{method:'POST',body:'{}'});box.innerHTML='';if(!r.devices?.length){box.className='device-list empty';box.textContent='No TV found automatically. Use the saved IP below.';return}r.devices.forEach(d=>box.append(deviceCard(d)));toast(`${r.devices.length} TV${r.devices.length===1?'':'s'} found`)}catch(e){box.className='device-list empty';box.textContent=`Scan error: ${e.message}`}}
async function connectTv(d){if(!(await testBridge(true)))return toast('Bridge is offline');try{const r=await api('/api/connect',{method:'POST',body:JSON.stringify(d)}),tv={...d,...r.device,id:r.device?.id||d.id||`philips:${d.ip}`,secureCredentials:r.secureCredentials};state.current=tv;const i=state.devices.findIndex(x=>x.id===tv.id||x.ip===tv.ip);if(i>=0)state.devices[i]=tv;else state.devices.unshift(tv);save();renderDevices();await refreshStatus();toast(`Connected • ${tv.ip} • no new pairing`);go('home')}catch(e){toast(e.data?.temporary?'TV API temporarily unavailable. Saved selection kept.':`Connect failed: ${e.message}`)}}
function controlError(e){if(e.data?.code==='secure_control_required')return 'This button is secure-only on your TV. The current connection stays active; no PIN was started.';return e.message}
async function key(k){vib();if(!state.current)return toast('Connect a TV first');try{await api('/api/key',{method:'POST',body:JSON.stringify({deviceId:state.current.id,key:k})});toast(`${k} sent`)}catch(e){toast(`TV command: ${controlError(e)}`);updateRemoteNotice(e)}}
function yes(v){return v?'Yes':'No'}
async function refreshStatus(){if(!state.current||!state.bridgeOnline)return;try{const s=await api(`/api/status?deviceId=${encodeURIComponent(state.current.id)}`);state.status=s;state.current.secureCredentials=s.secureCredentials;save();$('#statVolume').textContent=Number.isFinite(s.volume)?s.volume:'—';$('#volumeValue').textContent=Number.isFinite(s.volume)?s.volume:'—';if(Number.isFinite(s.volume))$('#volumeSlider').value=s.volume;$('#statMute').textContent=s.muted===true?'Muted':s.muted===false?'Sound on':'Unknown';const source=s.source||s.app||'—';$('#statSource').textContent=source;$('#screenSource').textContent=source==='—'?'TV connected':source;$('#statAmbilight').textContent=s.ambilight||'—';$('#statApi').textContent=`${s.apiMode||'TV'} • API ${s.apiVersion||'?'}${s.secureCredentials?' • secure saved':''}`;const c=s.capabilities||{},spans=$$('#capabilities span');[c.volume,c.activities,c.inputkey,c.applications,c.ambilight,s.secureCredentials].forEach((v,i)=>{if(spans[i])spans[i].querySelector('b').textContent=yes(v)});updateCurrentUi();updateRemoteNotice()}catch(e){toast(`Status: ${e.message}`)}}
function updateRemoteNotice(error){const n=$('#remoteNotice');if(!n)return;const secure=state.status?.secureCredentials||state.current?.secureCredentials,input=state.status?.capabilities?.inputkey;if(!state.current){n.className='notice';n.textContent='Connect a TV first.';return}if(error?.data?.code==='secure_control_required'||(input&&secure===false)){n.className='notice warning';n.textContent='Your TV reports input-key support, but this firmware protects remote commands behind the secure JointSpace connection. The existing HTTP connection remains untouched; buttons will not trigger a new PIN.';return}n.className='notice success';n.textContent=secure?'Secure control credentials are saved; remote commands can fall back to HTTPS automatically.':'Remote availability is being detected per command.'}
async function setVolume(v){if(!state.current)return;$('#volumeValue').textContent=v;try{await api('/api/volume',{method:'POST',body:JSON.stringify({deviceId:state.current.id,volume:Number(v)})});$('#statVolume').textContent=v}catch(e){toast(`Volume: ${controlError(e)}`)}}
async function toggleMute(){if(!state.current)return;const next=state.status?.muted!==true;try{await api('/api/mute',{method:'POST',body:JSON.stringify({deviceId:state.current.id,muted:next})});await refreshStatus()}catch(e){toast(`Mute: ${controlError(e)}`)}}
async function loadApps(){const box=$('#appsGrid'),status=$('#appsStatus');if(!state.current){box.className='apps-grid empty';box.textContent='Connect a TV to load apps.';return}box.className='apps-grid';box.innerHTML='<div class="loading-card">Checking application endpoint…</div>';try{const r=await api(`/api/apps?deviceId=${encodeURIComponent(state.current.id)}`);box.innerHTML='';if(r.unavailable){status.className='notice warning';status.textContent=`Installed app list is not exposed on this firmware (${r.reason}). This is a TV API limitation, not a lost connection.`;box.className='apps-grid empty';box.textContent='Application tiles are hidden because the TV did not return a list.';return}status.className='notice success';status.textContent=`${r.apps.length} applications returned by the TV.`;if(!r.apps.length){box.className='apps-grid empty';box.textContent='The TV returned an empty application list.';return}r.apps.forEach(a=>{const b=document.createElement('button');b.className='app-tile';b.innerHTML=`<span class="app-icon">${(a.name||'?')[0].toUpperCase()}</span><b>${a.name||'App'}</b><small>Open on TV</small>`;b.onclick=async()=>{try{await api('/api/apps/launch',{method:'POST',body:JSON.stringify({deviceId:state.current.id,app:a})});toast(`Opening ${a.name}`)}catch(e){toast(`App launch: ${controlError(e)}`)}};box.append(b)})}catch(e){status.className='notice warning';status.textContent=`Apps unavailable: ${e.message}`;box.className='apps-grid empty';box.textContent='No app list available.'}}
function styleFor(name){return (state.ambiInfo?.styles||[]).find(s=>(s.styleName||s.name)===name)}
function presetOptions(mode){const s=styleFor(mode);if(mode==='FOLLOW_AUDIO')return s?.algorithms||s?.menuSettings||fallbackPresets[mode];if(mode==='FOLLOW_VIDEO'||mode==='FOLLOW_COLOR')return s?.menuSettings||fallbackPresets[mode];return fallbackPresets[mode]||['STANDARD']}
function refreshAmbiForm(){const mode=$('#ambiMode').value,preset=$('#ambiPreset'),opts=presetOptions(mode);preset.innerHTML='';opts.forEach(x=>{const o=document.createElement('option');o.value=x;o.textContent=x.replaceAll('_',' ').toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());preset.append(o)});$('#ambiColorLabel').classList.toggle('hidden',mode!=='FOLLOW_COLOR');$('#ambiTuningLabel').classList.toggle('hidden',mode!=='FOLLOW_AUDIO');$('#ambiPresetLabel').classList.toggle('hidden',mode==='OFF')}
async function applyAmbilight(modeOverride){if(!state.current)return toast('Connect a TV first');if(modeOverride)$('#ambiMode').value=modeOverride;refreshAmbiForm();const mode=$('#ambiMode').value,payload={deviceId:state.current.id,mode,preset:$('#ambiPreset').value,algorithm:$('#ambiPreset').value,tuning:Number($('#ambiTuning').value),color:$('#ambiColor').value};try{await api('/api/ambilight',{method:'POST',body:JSON.stringify(payload)});toast(`Ambilight • ${mode.replaceAll('_',' ')}`);await Promise.all([refreshStatus(),loadAmbilightInfo()])}catch(e){toast(`Ambilight: ${controlError(e)}`)}}
function renderAmbiInfo(){const i=state.ambiInfo,box=$('#ambiInfo');if(!i){box.textContent='No Ambilight data loaded.';return}const names=(i.styles||[]).map(s=>s.styleName||s.name).filter(Boolean),t=i.topology||{};box.innerHTML=`<div class="mini-stat"><span>Current</span><b>${i.current?.styleName||'—'} ${i.current?.menuSetting?'/ '+i.current.menuSetting:''}</b></div><div class="mini-stat"><span>Supported styles</span><b>${names.length?names.join(', '):'Not exposed'}</b></div><div class="mini-stat"><span>LED topology</span><b>Left ${t.left||0} • Top ${t.top||0} • Right ${t.right||0}</b></div>`}
async function loadAmbilightInfo(){if(!state.current)return;try{state.ambiInfo=await api(`/api/ambilight/info?deviceId=${encodeURIComponent(state.current.id)}`);renderAmbiInfo();const current=state.ambiInfo.current?.styleName;if(current&&['FOLLOW_VIDEO','FOLLOW_AUDIO','FOLLOW_COLOR','FLAG','OFF'].includes(current))$('#ambiMode').value=current;refreshAmbiForm()}catch(e){$('#ambiInfo').textContent=`Ambilight info unavailable: ${e.message}`}}
function renderZones(){$$('.zone').forEach(b=>b.classList.toggle('active',state.zones[b.dataset.zone]!==false))}
async function applyZones(){if(!state.current)return toast('Connect a TV first');const payload={deviceId:state.current.id,color:$('#zoneColor').value,zones:state.zones};try{await api('/api/ambilight/zones',{method:'POST',body:JSON.stringify(payload)});$('#zoneModeHint').textContent='Manual custom zone mode active';toast('Custom zones applied')}catch(e){toast(`Zones: ${controlError(e)}`)}}
async function loadAndroidInfo(){if(!state.current)return;try{const r=await api(`/api/android/info?deviceId=${encodeURIComponent(state.current.id)}`),sys=r.system||{},feat=sys.featuring||{},json=feat.jsonfeatures||{},system=feat.systemfeatures||{};$('#androidOs').textContent=system.os_type||system.tvtype||'Philips TV';const act=r.activity||{};$('#androidActivity').textContent=act.channel?.name||act.intent?.component?.packageName||act.component?.label||'—';$('#androidStorage').textContent=r.availability.storage?'Available':'Not exposed';$('#androidTime').textContent=r.timestamp?.timestamp||r.timestamp?.time||'—';const fbox=$('#androidFeatures');fbox.innerHTML='';Object.entries(json).forEach(([k,v])=>{const row=document.createElement('div');row.className='feature-row';row.innerHTML=`<b>${k}</b><span>${Array.isArray(v)?v.join(', '):JSON.stringify(v)}</span>`;fbox.append(row)});if(!fbox.children.length)fbox.textContent='No jsonfeatures returned.';const vals=[r.availability.channels,r.availability.recordings,!!json.applications,!!json.inputkey,!!json.textentry,!!json.activities];$$('#androidServices span b').forEach((b,i)=>b.textContent=yes(vals[i]));$('#androidRaw').textContent=JSON.stringify({activity:r.activity,storage:r.storage,channels:r.channels,recordings:r.recordings},null,2)}catch(e){toast(`Android TV: ${e.message}`)}}
function pick(obj,keys){for(const k of keys){if(obj&&obj[k]!=null)return obj[k]}return '—'}
async function loadInfo(){if(!state.current)return;try{const r=await api(`/api/info?deviceId=${encodeURIComponent(state.current.id)}`),cells=$$('#tvInfoGrid span b'),sys=r.system||{},power=r.power||{},vals=[pick(sys,['name','serialnumber'])||state.current.name,pick(sys,['model','modelname'])||state.current.model,state.current.ip,`${r.device.apiMode||'—'} / API ${r.device.apiVersion||'?'}`,pick(power,['powerstate','power','current']),pick(sys,['softwareversion','software_version','version'])];vals.forEach((v,i)=>{if(cells[i])cells[i].textContent=v??'—'})}catch(e){toast(`TV info: ${e.message}`)}}
function manualAdd(){const ip=$('#manualIp').value.trim(),name=$('#manualName').value.trim()||'Philips TV';if(!/^\d{1,3}(\.\d{1,3}){3}$/.test(ip))return toast('Enter a valid local IPv4 address');connectTv({id:`philips:${ip}`,ip,name,brand:'philips'})}
$$('.nav').forEach(b=>b.onclick=()=>go(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$$('[data-key]').forEach(b=>b.onclick=()=>key(b.dataset.key));$$('[data-ambi-mode]').forEach(b=>b.onclick=()=>applyAmbilight(b.dataset.ambiMode));$$('.zone').forEach(b=>b.onclick=()=>{state.zones[b.dataset.zone]=!state.zones[b.dataset.zone];renderZones()});
$('#scanBtn').onclick=scan;$('#deviceScanBtn').onclick=scan;$('#connectBtn').onclick=()=>testBridge();$('#refreshStatusBtn').onclick=refreshStatus;$('#capRefreshBtn').onclick=refreshStatus;$('#manualAddBtn').onclick=manualAdd;$('#refreshAppsBtn').onclick=loadApps;$('#applyAmbiBtn').onclick=()=>applyAmbilight();$('#loadAmbiInfoBtn').onclick=loadAmbilightInfo;$('#applyZonesBtn').onclick=applyZones;$('#allZonesOnBtn').onclick=()=>{state.zones={left:true,top:true,right:true};renderZones()};$('#refreshAndroidBtn').onclick=loadAndroidInfo;$('#refreshInfoBtn').onclick=loadInfo;$('#muteBtn').onclick=toggleMute;$('#ambiMode').onchange=refreshAmbiForm;
$('#openDiagBtn').onclick=()=>{if(!state.current)return toast('Connect a TV first');window.open(`${state.bridgeUrl}/api/diagnose?ip=${encodeURIComponent(state.current.ip)}`,'_blank')};
$('#saveBridgeBtn').onclick=()=>{state.bridgeUrl=$('#bridgeUrl').value.trim().replace(/\/$/,'');localStorage.setItem('bridgeUrl',state.bridgeUrl);testBridge()};
$('#clearDataBtn').onclick=()=>{localStorage.removeItem('devices');localStorage.removeItem('currentTv');localStorage.removeItem('pairedTv');location.reload()};
let volumeTimer;$('#volumeSlider').oninput=e=>{clearTimeout(volumeTimer);$('#volumeValue').textContent=e.target.value;volumeTimer=setTimeout(()=>setVolume(e.target.value),180)};
for(let n=1;n<=9;n++){const b=document.createElement('button');b.textContent=n;b.onclick=()=>key(`Digit${n}`);$('#channelGrid').append(b)}[['0','Digit0'],['CH +','ChannelStepUp'],['CH −','ChannelStepDown']].forEach(([label,k])=>{const b=document.createElement('button');b.textContent=label;b.onclick=()=>key(k);$('#channelGrid').append(b)});
const paired=JSON.parse(localStorage.getItem('pairedTv')||'null');if(paired?.id){state.current=paired;const i=state.devices.findIndex(x=>x.id===paired.id||x.ip===paired.ip);if(i>=0)state.devices[i]={...state.devices[i],...paired};else state.devices.unshift(paired);save();localStorage.removeItem('pairedTv')}
$('#bridgeUrl').value=state.bridgeUrl;if(state.current?.ip)$('#manualIp').value=state.current.ip;renderDevices();renderZones();refreshAmbiForm();testBridge(true).then(ok=>{if(ok&&state.current)refreshStatus()});if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});setInterval(()=>{if(state.bridgeOnline&&state.current&&$('#autoConnect')?.checked)refreshStatus()},15000);