const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const runningFromBridge=location.hostname==='localhost'||location.hostname==='127.0.0.1'||/^192\.168\.|^10\.|^172\.(1[6-9]|2\d|3[01])\./.test(location.hostname);
const defaultBridge=runningFromBridge?location.origin:'http://localhost:8765';
const state={bridgeUrl:localStorage.getItem('bridgeUrl')||defaultBridge,bridgeOnline:false,devices:JSON.parse(localStorage.getItem('devices')||'[]'),current:JSON.parse(localStorage.getItem('currentTv')||'null'),status:null};
const titles={home:['Home','Control your Philips TV from one dashboard.'],remote:['Remote','Full Philips JointSpace remote control.'],apps:['Apps','Launch applications exposed by the TV.'],ambilight:['Ambilight','Control and inspect Philips Ambilight.'],info:['TV info','Live details and connection protection.'],devices:['Devices','Discover or reconnect without re-pairing.'],settings:['Settings','Configure the local bridge and controller.']};
function toast(msg){const t=$('#toast');if(!t)return;t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),4200)}
function vib(){if($('#haptics')?.checked&&navigator.vibrate)navigator.vibrate(16)}
function save(){localStorage.setItem('devices',JSON.stringify(state.devices));localStorage.setItem('currentTv',JSON.stringify(state.current))}
async function api(path,opts={}){const url=state.bridgeUrl.replace(/\/$/,'')+path,ctrl=new AbortController(),timeout=setTimeout(()=>ctrl.abort(),15000);try{const r=await fetch(url,{...opts,headers:{'Content-Type':'application/json',...(opts.headers||{})},signal:ctrl.signal});const text=await r.text();let data={};try{data=text?JSON.parse(text):{}}catch{data={message:text}}if(!r.ok){const e=new Error(data.error||data.message||`HTTP ${r.status}`);e.data=data;e.status=r.status;throw e}return data}catch(e){if(e.name==='AbortError')throw new Error('Bridge timed out');throw e}finally{clearTimeout(timeout)}}
function bridgeUi(on,detail=''){state.bridgeOnline=on;$('#bridgeDot')?.classList.toggle('online',on);if($('#bridgeStatus'))$('#bridgeStatus').textContent=on?'Bridge online':'Bridge offline';if($('#bridgeUrlLabel'))$('#bridgeUrlLabel').textContent=detail||state.bridgeUrl.replace(/^https?:\/\//,'');if($('#statConnection'))$('#statConnection').textContent=on?(state.current?'Connected':'Bridge ready'):'Offline'}
async function testBridge(silent=false){state.bridgeUrl=$('#bridgeUrl')?.value.trim()||state.bridgeUrl;try{const d=await api('/api/health');bridgeUi(true,`${(d.localIPv4s||[]).join(', ')||'localhost'} • v${d.version||'?'}`);if(!silent)toast(`Bridge online • v${d.version}`);return true}catch(e){bridgeUi(false,'localhost:8765 unavailable');if(!silent)toast(`Bridge offline: ${e.message}`);return false}}
function go(view){$$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${view}`));$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===view));if($('#pageTitle'))$('#pageTitle').textContent=titles[view][0];if($('#pageSub'))$('#pageSub').textContent=titles[view][1];if(view==='apps')loadApps();if(view==='info')loadInfo();if(view==='ambilight')loadAmbilightInfo()}
function deviceCard(d){const wrap=document.createElement('div');wrap.className='device-item';const info=document.createElement('div');const b=document.createElement('b');b.textContent=d.name||d.model||'Philips TV';const s=document.createElement('small');s.textContent=`PHILIPS • ${d.ip||'Unknown IP'}${d.model?' • '+d.model:''}${d.apiVersion?' • API '+d.apiVersion:''}`;info.append(b,s);const btn=document.createElement('button');btn.className='btn '+(state.current?.id===d.id?'secondary':'primary');btn.textContent=state.current?.id===d.id?'Connected':'Connect';btn.onclick=()=>connectTv(d);wrap.append(info,btn);return wrap}
function renderDevices(){const box=$('#savedDevices');if(!box)return;box.innerHTML='';if(!state.devices.length){box.className='device-list empty';box.textContent='No saved TVs yet.'}else{box.className='device-list';state.devices.forEach(d=>box.append(deviceCard(d)))}updateCurrentUi()}
function updateCurrentUi(){const c=state.current;$('#heroTvName')&&( $('#heroTvName').textContent=c?.name||'No TV connected');$('#heroTvMeta')&&( $('#heroTvMeta').textContent=c?`Philips • ${c.model||'Smart TV'} • ${c.ip} • saved connection`:'Connect your Philips TV once and the controller keeps using the saved connection.');$('#remoteDeviceName')&&( $('#remoteDeviceName').textContent=c?.name||'No TV');$('#screenStatus')&&( $('#screenStatus').textContent=c?'CONNECTED':'OFFLINE');const badge=$('#connectionBadge');if(badge){badge.textContent=c?'Connected':'Offline';badge.className=`badge ${c?'online':'offline'}`}}
async function scan(){if(!(await testBridge(true))){toast('Bridge is not reachable');return}const box=$('#scanResults');box.className='device-list';box.innerHTML='<div class="device-item"><div><b>Scanning network…</b><small>Saved TV first, then SSDP and LAN probe.</small></div></div>';try{const r=await api('/api/discover',{method:'POST',body:'{}'});box.innerHTML='';if(!r.devices?.length){box.className='device-list empty';box.textContent='No TV found automatically. Your saved/manual IP can still be used.';return}r.devices.forEach(d=>box.append(deviceCard(d)));toast(`${r.devices.length} TV${r.devices.length===1?'':'s'} found`)}catch(e){box.className='device-list empty';box.textContent=`Scan error: ${e.message}`}}
async function connectTv(d){if(!(await testBridge(true))){toast('Bridge is offline');return}try{const r=await api('/api/connect',{method:'POST',body:JSON.stringify(d)});const tv={...d,...r.device,id:r.device?.id||d.id||`philips:${d.ip}`};state.current=tv;const i=state.devices.findIndex(x=>x.id===tv.id||x.ip===tv.ip);if(i>=0)state.devices[i]=tv;else state.devices.unshift(tv);save();renderDevices();await refreshStatus();toast(`Connected • ${tv.ip} • no new pairing requested`);go('home')}catch(e){if(e.data?.temporary){toast('TV API is temporarily unavailable. Saved connection kept; no PIN requested.');return}if(e.data?.needsPairing||e.data?.needsCredentials){toast('Secure pairing is only needed if HTTP mode stops working completely.');return}toast(`Connect failed: ${e.message}`)}}
async function key(k){vib();if(!state.current){toast('Connect a TV first');return}try{await api('/api/key',{method:'POST',body:JSON.stringify({deviceId:state.current.id,key:k})});toast(`${k} sent`)}catch(e){toast(`TV command failed: ${e.message}`)}}
function capWord(v){return v?'Yes':'No'}
async function refreshStatus(){if(!state.current||!state.bridgeOnline)return;try{const s=await api(`/api/status?deviceId=${encodeURIComponent(state.current.id)}`);state.status=s;$('#statVolume')&&( $('#statVolume').textContent=Number.isFinite(s.volume)?s.volume:'—');$('#volumeValue')&&( $('#volumeValue').textContent=Number.isFinite(s.volume)?s.volume:'—');if(Number.isFinite(s.volume)&&$('#volumeSlider'))$('#volumeSlider').value=s.volume;$('#statMute')&&( $('#statMute').textContent=s.muted===true?'Muted':s.muted===false?'Sound on':'Unknown');const source=s.source||s.app||'—';$('#statSource')&&( $('#statSource').textContent=source);$('#screenSource')&&( $('#screenSource').textContent=source==='—'?'TV connected':source);$('#statAmbilight')&&( $('#statAmbilight').textContent=s.ambilight||'—');$('#statApi')&&( $('#statApi').textContent=`${s.apiMode||'TV'} • API ${s.apiVersion||'?'}`);const c=s.capabilities||{};const spans=$$('#capabilities span');[['volume',c.volume],['activity',c.activities],['power',c.power],['ambilight',c.ambilight]].forEach(([name,v],i)=>{if(spans[i])spans[i].querySelector('b').textContent=capWord(v)});updateCurrentUi()}catch(e){toast(`Status: ${e.message}`)}}
async function setVolume(v){if(!state.current)return;$('#volumeValue')&&( $('#volumeValue').textContent=v);try{await api('/api/volume',{method:'POST',body:JSON.stringify({deviceId:state.current.id,volume:Number(v)})});$('#statVolume')&&( $('#statVolume').textContent=v)}catch(e){toast(`Volume: ${e.message}`)}}
async function toggleMute(){if(!state.current)return;const next=state.status?.muted!==true;try{await api('/api/mute',{method:'POST',body:JSON.stringify({deviceId:state.current.id,muted:next})});toast(next?'Muted':'Unmuted');await refreshStatus()}catch(e){toast(`Mute: ${e.message}`)}}
async function loadApps(){const box=$('#appsGrid');if(!box)return;if(!state.current){box.className='apps-grid empty';box.textContent='Connect a TV to load apps.';return}box.className='apps-grid';box.innerHTML='<div class="loading-card">Loading installed applications…</div>';try{const r=await api(`/api/apps?deviceId=${encodeURIComponent(state.current.id)}`);box.innerHTML='';if(!r.apps?.length){box.className='apps-grid empty';box.textContent='This firmware does not expose the application list on the available JointSpace routes.';return}r.apps.forEach(a=>{const b=document.createElement('button');b.className='app-tile';b.innerHTML=`<span class="app-icon">${(a.name||'?')[0].toUpperCase()}</span><b>${a.name||'App'}</b><small>Open on TV</small>`;b.onclick=async()=>{try{await api('/api/apps/launch',{method:'POST',body:JSON.stringify({deviceId:state.current.id,app:a})});toast(`Opening ${a.name}`)}catch(e){toast(`App launch: ${e.message}`)}};box.append(b)})}catch(e){box.className='apps-grid empty';box.textContent=`Apps unavailable: ${e.message}`}}
async function applyAmbilight(modeOverride){if(!state.current){toast('Connect a TV first');return}if(modeOverride)$('#ambiMode').value=modeOverride;const payload={deviceId:state.current.id,mode:$('#ambiMode').value,menuSetting:$('#ambiPreset').value,color:$('#ambiColor').value};try{await api('/api/ambilight',{method:'POST',body:JSON.stringify(payload)});toast(`Ambilight: ${payload.mode}`);await refreshStatus()}catch(e){toast(`Ambilight: ${e.message}`)}}
async function loadAmbilightInfo(){const box=$('#ambiInfo');if(!box||!state.current)return;box.innerHTML='Loading…';try{const [styles,topology]=await Promise.all([api(`/api/ambilight/styles?deviceId=${encodeURIComponent(state.current.id)}`),api(`/api/ambilight/topology?deviceId=${encodeURIComponent(state.current.id)}`)]);const names=(styles.styles||[]).map(x=>x.styleName||x.name).filter(Boolean);box.innerHTML=`<div class="mini-stat"><span>Styles</span><b>${names.length?names.join(', '):'Not exposed'}</b></div><div class="mini-stat"><span>Topology</span><b>${Object.keys(topology||{}).length?JSON.stringify(topology):'Not exposed'}</b></div>`}catch(e){box.textContent=`Ambilight info unavailable: ${e.message}`}}
function pick(obj,keys){for(const k of keys){if(obj&&obj[k]!=null)return obj[k]}return '—'}
async function loadInfo(){if(!state.current)return;try{const r=await api(`/api/info?deviceId=${encodeURIComponent(state.current.id)}`),cells=$$('#tvInfoGrid span b'),sys=r.system||{},power=r.power||{};const vals=[pick(sys,['name','serialnumber'])||state.current.name,pick(sys,['model','modelname'])||state.current.model,state.current.ip,`${r.device.apiMode||'—'} / API ${r.device.apiVersion||'?'}`,pick(power,['powerstate','power','current']),pick(sys,['softwareversion','software_version','version'])];vals.forEach((v,i)=>{if(cells[i])cells[i].textContent=v??'—'})}catch(e){toast(`TV info: ${e.message}`)}}
function manualAdd(){const ip=$('#manualIp').value.trim(),name=$('#manualName').value.trim()||'Philips TV';if(!/^\d{1,3}(\.\d{1,3}){3}$/.test(ip)){toast('Enter a valid local IPv4 address');return}connectTv({id:`philips:${ip}`,ip,name,brand:'philips'})}
$$('.nav').forEach(b=>b.onclick=()=>go(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$$('[data-key]').forEach(b=>b.onclick=()=>key(b.dataset.key));$$('[data-ambi]').forEach(b=>b.onclick=()=>applyAmbilight(b.dataset.ambi));
$('#scanBtn').onclick=scan;$('#deviceScanBtn').onclick=scan;$('#connectBtn').onclick=()=>testBridge();$('#refreshStatusBtn').onclick=refreshStatus;$('#capRefreshBtn').onclick=refreshStatus;$('#manualAddBtn').onclick=manualAdd;$('#refreshAppsBtn').onclick=loadApps;$('#applyAmbiBtn').onclick=()=>applyAmbilight();$('#loadAmbiInfoBtn').onclick=loadAmbilightInfo;$('#refreshInfoBtn').onclick=loadInfo;$('#muteBtn').onclick=toggleMute;
$('#openDiagBtn').onclick=()=>{if(!state.current)return toast('Connect a TV first');window.open(`${state.bridgeUrl}/api/diagnose?ip=${encodeURIComponent(state.current.ip)}`,'_blank')};
$('#saveBridgeBtn').onclick=()=>{state.bridgeUrl=$('#bridgeUrl').value.trim().replace(/\/$/,'');localStorage.setItem('bridgeUrl',state.bridgeUrl);testBridge()};
$('#clearDataBtn').onclick=()=>{localStorage.removeItem('devices');localStorage.removeItem('currentTv');localStorage.removeItem('pairedTv');location.reload()};
let volumeTimer;$('#volumeSlider').oninput=e=>{clearTimeout(volumeTimer);$('#volumeValue').textContent=e.target.value;volumeTimer=setTimeout(()=>setVolume(e.target.value),170)};
for(let n=1;n<=9;n++){const b=document.createElement('button');b.textContent=n;b.onclick=()=>key(`Digit${n}`);$('#channelGrid').append(b)};[['0','Digit0'],['CH +','ChannelStepUp'],['CH −','ChannelStepDown']].forEach(([label,k])=>{const b=document.createElement('button');b.textContent=label;b.onclick=()=>key(k);$('#channelGrid').append(b)});
const paired=JSON.parse(localStorage.getItem('pairedTv')||'null');if(paired?.id){state.current=paired;const i=state.devices.findIndex(x=>x.id===paired.id||x.ip===paired.ip);if(i>=0)state.devices[i]={...state.devices[i],...paired};else state.devices.unshift(paired);save();localStorage.removeItem('pairedTv')}
$('#bridgeUrl').value=state.bridgeUrl;if(state.current?.ip&&!$('#manualIp').value)$('#manualIp').value=state.current.ip;renderDevices();testBridge(true).then(ok=>{if(ok&&state.current)refreshStatus()});if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});setInterval(()=>{if(state.bridgeOnline&&state.current&&$('#autoConnect')?.checked)refreshStatus()},12000);