(() => {
  const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
  const POS={1:'Links boven',0:'Rechts boven',4:'Midden',3:'Links onder',2:'Rechts onder'};
  const PRESETS={philips:{name:'Philips',title:'#FFFFFF',message:'#FFFFFF',bg:'#E6111820',ts:18,ms:34},blue:{name:'Blauw',title:'#8DCCFF',message:'#FFFFFF',bg:'#EC0A1828',ts:18,ms:36},warning:{name:'Waarschuwing',title:'#FFD86B',message:'#FFFFFF',bg:'#F12A1705',ts:20,ms:38},minimal:{name:'Minimal',title:'#DDE5EE',message:'#FFFFFF',bg:'#D90A0D12',ts:16,ms:32}};
  let statusTimer=null,previewTimer=null,previewEnd=0,selectedPosition=4;

  function inject(){
    if($('#view-countdown'))return;
    const st=document.createElement('style');st.textContent=`
      .cd-grid{display:grid;grid-template-columns:minmax(430px,1.05fr) minmax(360px,.95fr);gap:18px}.cd-time-inputs{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.cd-time-box{border:1px solid var(--line);border-radius:14px;padding:12px;background:rgba(255,255,255,.025)}.cd-time-box input{font-size:28px;font-weight:800;text-align:center}.cd-time-box span{display:block;text-align:center;color:var(--muted);font-size:11px;margin-top:4px;text-transform:uppercase;letter-spacing:.08em}.cd-presets,.cd-actions,.cd-quick{display:flex;gap:8px;flex-wrap:wrap}.cd-section{padding:14px 0;border-top:1px solid var(--line)}.cd-section:first-of-type{border-top:0}.cd-section-title{display:flex;justify-content:space-between;gap:12px;align-items:center;margin-bottom:10px}.cd-style-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.cd-color{display:grid;grid-template-columns:1fr 78px;gap:8px;align-items:end}.cd-color input[type=color]{height:42px;padding:2px}.cd-screen{position:relative;aspect-ratio:16/9;border-radius:18px;overflow:hidden;background:radial-gradient(circle at 50% 35%,#1b2637,#070a10 72%);border:1px solid #ffffff18}.cd-overlay{position:absolute;min-width:260px;max-width:70%;padding:15px 18px;border-radius:10px;box-shadow:0 18px 55px #0009;transition:.25s}.cd-overlay[data-pos='1']{top:5%;left:3%}.cd-overlay[data-pos='0']{top:5%;right:3%}.cd-overlay[data-pos='4']{top:50%;left:50%;transform:translate(-50%,-50%)}.cd-overlay[data-pos='3']{bottom:5%;left:3%}.cd-overlay[data-pos='2']{bottom:5%;right:3%}.cd-preview-title{font-weight:800;letter-spacing:.08em}.cd-preview-label{margin-top:5px;opacity:.8}.cd-preview-time{font-variant-numeric:tabular-nums;font-weight:900;letter-spacing:.06em;margin-top:6px;white-space:nowrap}.cd-position-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:7px}.cd-position-grid button.active{outline:2px solid #6bb8ff;background:#6bb8ff18}.cd-position-grid .center-btn{grid-column:2}.cd-status-card{display:grid;grid-template-columns:1fr auto;gap:12px;align-items:center;padding:14px;border:1px solid var(--line);border-radius:14px}.cd-status-time{font-size:30px;font-weight:900;font-variant-numeric:tabular-nums}.cd-dot{width:9px;height:9px;border-radius:50%;background:#777;display:inline-block;margin-right:7px}.cd-dot.live{background:#39d98a;box-shadow:0 0 12px #39d98a}.cd-dot.paused{background:#f5bd55}.cd-switch{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:10px 12px;border:1px solid var(--line);border-radius:12px}.cd-switch input{width:18px;height:18px}@media(max-width:1000px){.cd-grid{grid-template-columns:1fr}}@media(max-width:650px){.cd-time-inputs{grid-template-columns:1fr 1fr}.cd-style-grid{grid-template-columns:1fr}.cd-position-grid{grid-template-columns:repeat(2,1fr)}.cd-position-grid .center-btn{grid-column:auto}}
    `;document.head.append(st);
    const nav=$('.sidebar nav'),settings=nav?.querySelector('[data-view="settings"]');const n=document.createElement('button');n.className='nav';n.dataset.view='countdown';n.innerHTML='⏱ <span>Countdown</span>';nav.insertBefore(n,settings||null);
    const v=document.createElement('section');v.className='view';v.id='view-countdown';v.innerHTML=`
      <div class="cd-grid">
        <div class="card">
          <div class="card-head"><div><span class="eyebrow">TV COUNTDOWN</span><h3>⏱ Countdown Studio</h3><p>Zet een live aftellende timer op je TV. De bridge ververst hem elke seconde via PiPup.</p></div><span class="badge protected">Native PiPup</span></div>
          <div class="cd-section"><div class="cd-section-title"><b>Tijd instellen</b><span class="muted">dagen : uren : minuten : seconden</span></div><div class="cd-time-inputs">
            <label class="cd-time-box"><input id="cdDays" type="number" min="0" max="3650" value="0"><span>Dagen</span></label>
            <label class="cd-time-box"><input id="cdHours" type="number" min="0" max="23" value="0"><span>Uren</span></label>
            <label class="cd-time-box"><input id="cdMinutes" type="number" min="0" max="59" value="5"><span>Minuten</span></label>
            <label class="cd-time-box"><input id="cdSeconds" type="number" min="0" max="59" value="0"><span>Seconden</span></label>
          </div><div class="cd-quick" style="margin-top:10px"><button class="btn ghost" data-quick="60">1 min</button><button class="btn ghost" data-quick="300">5 min</button><button class="btn ghost" data-quick="600">10 min</button><button class="btn ghost" data-quick="1800">30 min</button><button class="btn ghost" data-quick="3600">1 uur</button><button class="btn ghost" data-quick="86400">1 dag</button></div></div>
          <div class="cd-section"><div class="cd-section-title"><b>Tekst</b></div><div class="cd-style-grid"><label>Titel<input id="cdTitle" maxlength="80" value="COUNTDOWN"></label><label>Subtekst<input id="cdLabel" maxlength="120" placeholder="Bijv. Film start over"></label></div></div>
          <div class="cd-section"><div class="cd-section-title"><b>Locatie op TV</b><span id="cdPositionName" class="badge protected">Midden</span></div><div class="cd-position-grid"><button class="btn ghost" data-cdpos="1">Links boven</button><button class="btn ghost" data-cdpos="0">Rechts boven</button><button class="btn ghost center-btn active" data-cdpos="4">Midden</button><button class="btn ghost" data-cdpos="3">Links onder</button><button class="btn ghost" data-cdpos="2">Rechts onder</button></div><div class="notice subtle" style="margin-top:10px">Dit zijn de 5 echte native PiPup-posities; zo vermijden we weer dat witte WebView-vlak.</div></div>
          <div class="cd-section"><div class="cd-section-title"><b>Stijl</b><div class="cd-presets">${Object.entries(PRESETS).map(([k,p])=>`<button class="btn ghost" data-cdpreset="${k}">${p.name}</button>`).join('')}</div></div><div class="cd-style-grid">
            <div class="cd-color"><label>Titelkleur<input id="cdTitleColor" type="color" value="#FFFFFF"></label><input id="cdTitleColorHex" value="#FFFFFF" maxlength="9"></div>
            <div class="cd-color"><label>Timerkleur<input id="cdMessageColor" type="color" value="#FFFFFF"></label><input id="cdMessageColorHex" value="#FFFFFF" maxlength="9"></div>
            <div class="cd-color"><label>Achtergrond<input id="cdBgColor" type="color" value="#111820"></label><input id="cdBgColorHex" value="#E6111820" maxlength="9"></div>
            <div><div class="cd-section-title" style="margin-bottom:4px"><span>Titelgrootte</span><b id="cdTitleSizeVal">18 px</b></div><input id="cdTitleSize" type="range" min="8" max="40" value="18"></div>
            <div><div class="cd-section-title" style="margin-bottom:4px"><span>Timergrootte</span><b id="cdMessageSizeVal">34 px</b></div><input id="cdMessageSize" type="range" min="14" max="60" value="34"></div>
          </div></div>
          <div class="cd-section"><div class="cd-section-title"><b>Na afloop</b></div><label class="cd-switch"><span>Toon korte eindmelding</span><input id="cdShowFinished" type="checkbox" checked></label><div class="cd-style-grid" style="margin-top:10px"><label>Eindtitel<input id="cdFinishedTitle" maxlength="80" value="COUNTDOWN"></label><label>Eindmelding<input id="cdFinishedMessage" maxlength="160" value="Tijd is voorbij!"></label></div></div>
          <div class="cd-actions"><button id="cdPreviewBtn" class="btn ghost">▶ Preview starten</button><button id="cdStartBtn" class="btn primary">⏱ Start op TV</button><button id="cdPauseBtn" class="btn secondary">⏸ Pauze</button><button id="cdResumeBtn" class="btn secondary">▶ Hervat</button><button id="cdStopBtn" class="btn ghost">■ Verwijder van TV</button></div><div id="cdMessage" class="notice subtle" style="margin-top:12px">Klaar om een countdown te starten.</div>
        </div>
        <div>
          <div class="card"><div class="card-head"><div><h3>Live preview</h3><p>Voorbeeld van de native timerkaart.</p></div><span id="cdPreviewPos" class="badge protected">Midden</span></div><div class="cd-screen"><div id="cdOverlay" class="cd-overlay" data-pos="4"><div id="cdPreviewTitle" class="cd-preview-title">COUNTDOWN</div><div id="cdPreviewLabel" class="cd-preview-label"></div><div id="cdPreviewTime" class="cd-preview-time">00:00:05:00</div></div></div></div>
          <div class="card" style="margin-top:16px"><div class="card-head"><div><h3>Actieve countdown</h3><p>Status komt rechtstreeks van de bridge.</p></div><button id="cdRefresh" class="btn ghost">↻</button></div><div class="cd-status-card"><div><div><span id="cdStatusDot" class="cd-dot"></span><b id="cdStatusText">Geen actieve countdown</b></div><div id="cdStatusTime" class="cd-status-time">--:--:--:--</div><small id="cdStatusMeta" class="muted">Nog niets actief op de TV.</small></div><span id="cdStateBadge" class="badge offline">IDLE</span></div></div>
        </div>
      </div>`;
    document.querySelector('main').append(v);bind();applyPreset('philips');syncPreview();refreshStatus();statusTimer=setInterval(refreshStatus,1000);
  }

  function open(){ $$('.view').forEach(v=>v.classList.toggle('active',v.id==='view-countdown'));$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view==='countdown'));$('#pageTitle').textContent='Countdown Studio';$('#pageSub').textContent='Live aftellende timers op je Philips TV via PiPup.'}
  function deviceId(){return typeof state!=='undefined'&&state?.current?(state.current.id||(state.current.ip?`philips:${state.current.ip}`:null)):null}
  function msg(t,type='subtle'){const x=$('#cdMessage');x.className='notice '+type;x.textContent=t}
  function num(id,min,max){let n=Number($('#'+id).value||0);n=Math.max(min,Math.min(max,Number.isFinite(n)?n:0));$('#'+id).value=n;return n}
  function totalSeconds(){return num('cdDays',0,3650)*86400+num('cdHours',0,23)*3600+num('cdMinutes',0,59)*60+num('cdSeconds',0,59)}
  function fmt(sec){sec=Math.max(0,Math.ceil(sec));const d=Math.floor(sec/86400),h=Math.floor(sec%86400/3600),m=Math.floor(sec%3600/60),s=sec%60;return [d,h,m,s].map(x=>String(x).padStart(2,'0')).join(':')}
  function setQuick(sec){$('#cdDays').value=Math.floor(sec/86400);sec%=86400;$('#cdHours').value=Math.floor(sec/3600);sec%=3600;$('#cdMinutes').value=Math.floor(sec/60);$('#cdSeconds').value=sec%60;syncPreview()}
  function syncPreview(){const o=$('#cdOverlay');o.dataset.pos=String(selectedPosition);$('#cdPositionName').textContent=POS[selectedPosition];$('#cdPreviewPos').textContent=POS[selectedPosition];$('#cdPreviewTitle').textContent=$('#cdTitle').value||'COUNTDOWN';$('#cdPreviewLabel').textContent=$('#cdLabel').value||'';$('#cdPreviewTime').textContent=fmt(totalSeconds());$('#cdPreviewTitle').style.color=$('#cdTitleColorHex').value;$('#cdPreviewTime').style.color=$('#cdMessageColorHex').value;$('#cdPreviewLabel').style.color=$('#cdMessageColorHex').value;$('#cdPreviewTitle').style.fontSize=$('#cdTitleSize').value+'px';$('#cdPreviewTime').style.fontSize=$('#cdMessageSize').value+'px';o.style.background=$('#cdBgColorHex').value}
  function applyPreset(name){const p=PRESETS[name];if(!p)return;$('#cdTitleColor').value=p.title;$('#cdTitleColorHex').value=p.title;$('#cdMessageColor').value=p.message;$('#cdMessageColorHex').value=p.message;$('#cdBgColor').value='#'+p.bg.slice(-6);$('#cdBgColorHex').value=p.bg;$('#cdTitleSize').value=p.ts;$('#cdMessageSize').value=p.ms;$('#cdTitleSizeVal').textContent=p.ts+' px';$('#cdMessageSizeVal').textContent=p.ms+' px';$$('[data-cdpreset]').forEach(b=>b.classList.toggle('active',b.dataset.cdpreset===name));syncPreview()}
  function payload(){return {deviceId:deviceId(),days:num('cdDays',0,3650),hours:num('cdHours',0,23),minutes:num('cdMinutes',0,59),seconds:num('cdSeconds',0,59),position:selectedPosition,title:$('#cdTitle').value.trim(),label:$('#cdLabel').value.trim(),titleColor:$('#cdTitleColorHex').value.toUpperCase(),messageColor:$('#cdMessageColorHex').value.toUpperCase(),backgroundColor:$('#cdBgColorHex').value.toUpperCase(),titleSize:Number($('#cdTitleSize').value),messageSize:Number($('#cdMessageSize').value),showDays:true,showFinished:$('#cdShowFinished').checked,finishedTitle:$('#cdFinishedTitle').value.trim(),finishedMessage:$('#cdFinishedMessage').value.trim()}}
  async function start(){if(totalSeconds()<1)return msg('Stel minimaal 1 seconde in.','warning');const b=$('#cdStartBtn');b.disabled=true;b.textContent='Starten…';try{const r=await api('/api/countdown/start',{method:'POST',body:JSON.stringify(payload())});msg(`Countdown gestart op ${r.ip} • ${POS[selectedPosition]}.`,'success');refreshStatus()}catch(e){msg('Starten mislukt: '+e.message,'warning')}finally{b.disabled=false;b.textContent='⏱ Start op TV'}}
  async function action(path,ok){try{await api(path,{method:'POST',body:JSON.stringify({deviceId:deviceId()})});msg(ok,'success');refreshStatus()}catch(e){msg(e.message,'warning')}}
  async function refreshStatus(){try{const r=await api('/api/countdown/status');const dot=$('#cdStatusDot'),badge=$('#cdStateBadge');if(!r.active){dot.className='cd-dot';$('#cdStatusText').textContent='Geen actieve countdown';$('#cdStatusTime').textContent='--:--:--:--';$('#cdStatusMeta').textContent='Nog niets actief op de TV.';badge.className='badge offline';badge.textContent='IDLE';return}$('#cdStatusTime').textContent=r.display||'--:--:--:--';$('#cdStatusText').textContent=r.paused?'Countdown gepauzeerd':'Countdown actief';$('#cdStatusMeta').textContent=`${r.ip} • ${POS[r.position]||'TV'}${r.lastError?' • fout: '+r.lastError:''}`;dot.className='cd-dot '+(r.paused?'paused':'live');badge.className='badge protected';badge.textContent=r.paused?'PAUSED':'LIVE'}catch{}}
  function preview(){clearInterval(previewTimer);previewEnd=Date.now()+totalSeconds()*1000;if(previewEnd<=Date.now())return;$('#cdPreviewBtn').textContent='■ Preview stoppen';previewTimer=setInterval(()=>{const left=Math.max(0,Math.ceil((previewEnd-Date.now())/1000));$('#cdPreviewTime').textContent=fmt(left);if(left<=0){clearInterval(previewTimer);previewTimer=null;$('#cdPreviewBtn').textContent='▶ Preview starten';syncPreview()}},200)}
  function togglePreview(){if(previewTimer){clearInterval(previewTimer);previewTimer=null;$('#cdPreviewBtn').textContent='▶ Preview starten';syncPreview()}else preview()}
  function bind(){document.querySelector('[data-view="countdown"]').onclick=open;$$('[data-quick]').forEach(b=>b.onclick=()=>setQuick(Number(b.dataset.quick)));$$('[data-cdpos]').forEach(b=>b.onclick=()=>{$$('[data-cdpos]').forEach(x=>x.classList.remove('active'));b.classList.add('active');selectedPosition=Number(b.dataset.cdpos);syncPreview()});$$('[data-cdpreset]').forEach(b=>b.onclick=()=>applyPreset(b.dataset.cdpreset));['cdDays','cdHours','cdMinutes','cdSeconds','cdTitle','cdLabel'].forEach(id=>$('#'+id).addEventListener('input',syncPreview));[['cdTitleColor','cdTitleColorHex'],['cdMessageColor','cdMessageColorHex']].forEach(([c,h])=>{$('#'+c).oninput=e=>{$('#'+h).value=e.target.value.toUpperCase();syncPreview()};$('#'+h).oninput=syncPreview});$('#cdBgColor').oninput=e=>{$('#cdBgColorHex').value='#E6'+e.target.value.slice(1).toUpperCase();syncPreview()};$('#cdBgColorHex').oninput=syncPreview;$('#cdTitleSize').oninput=e=>{$('#cdTitleSizeVal').textContent=e.target.value+' px';syncPreview()};$('#cdMessageSize').oninput=e=>{$('#cdMessageSizeVal').textContent=e.target.value+' px';syncPreview()};$('#cdStartBtn').onclick=start;$('#cdPauseBtn').onclick=()=>action('/api/countdown/pause','Countdown gepauzeerd en van TV verborgen.');$('#cdResumeBtn').onclick=()=>action('/api/countdown/resume','Countdown hervat op TV.');$('#cdStopBtn').onclick=()=>action('/api/countdown/stop','Countdown gestopt en van TV verwijderd.');$('#cdPreviewBtn').onclick=togglePreview;$('#cdRefresh').onclick=refreshStatus}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',inject);else inject();
})();