(() => {
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  let paired=false,checking=false,volumeTimer=null,lastMute=false;
  const tv=()=>typeof state!=='undefined'&&state?state.current:null;
  const deviceId=()=>tv()?.id||(tv()?.ip?`philips:${tv().ip}`:null);
  function msg(text,type='subtle'){const el=$('#secureRemoteMessage');if(el){el.className='notice '+type;el.textContent=text}}
  function inject(){
    const view=$('#view-remote');if(!view||$('#secureRemoteCard'))return;
    const card=document.createElement('div');card.id='secureRemoteCard';card.className='card secure-remote-card';card.innerHTML=`
      <div class="card-head"><div><span class="eyebrow">SECURE CONTROL</span><h3>📱 Remote verbinding</h3><p>Eenmalig koppelen. Daarna bewaart de bridge de secure Philips-gegevens lokaal en wordt de koppeling automatisch hergebruikt.</p></div><span id="secureRemoteBadge" class="badge offline">Control controleren…</span></div>
      <div id="secureRemoteSetup" class="secure-remote-setup"><div class="secure-remote-explain"><b>Eenmalig activeren</b><span>Alleen de eerste keer verschijnt er een PIN op je TV. Daarna hoef je hem niet opnieuw in te voeren zolang devices.local.json blijft staan.</span></div><button id="secureRemoteStart" class="btn primary">Remote activeren</button></div>
      <div id="secureRemotePinBox" class="secure-pin-box hidden"><label>PIN van de TV<input id="secureRemotePin" inputmode="numeric" autocomplete="one-time-code" maxlength="8" placeholder="Bijv. 1234"></label><button id="secureRemoteGrant" class="btn primary">PIN bevestigen</button><button id="secureRemoteCancel" class="btn ghost">Annuleren</button></div>
      <div id="secureRemoteMessage" class="notice subtle">Opgeslagen Remote-koppeling controleren…</div>`;
    view.insertBefore(card,view.firstChild);bind();check();
  }
  function setPaired(v){paired=!!v;const badge=$('#secureRemoteBadge'),setup=$('#secureRemoteSetup'),pin=$('#secureRemotePinBox');if(badge){badge.textContent=paired?'Secure Remote klaar':'Control niet gekoppeld';badge.className='badge '+(paired?'protected':'offline')}if(setup)setup.classList.toggle('hidden',paired);if(paired&&pin)pin.classList.add('hidden');syncButtons();if(paired){const n=$('#remoteNotice');if(n){n.classList.add('hidden');n.textContent=''}msg('Remote-koppeling is onthouden. Geen nieuwe PIN nodig. De TV-knop schakelt naar HDMI 1.','success')}}
  function syncButtons(){if(!paired)return;$$('[data-key],#muteBtn,#volumeSlider').forEach(x=>{x.disabled=false;x.removeAttribute('aria-disabled')})}
  async function check(){if(checking)return;const id=deviceId();if(!id)return setTimeout(check,700);checking=true;try{const r=await api('/api/remote/status',{method:'POST',body:JSON.stringify({deviceId:id})});setPaired(!!r.paired);if(!r.paired)msg('Ambilight is verbonden. Activeer Remote één keer om secure bediening op te slaan.')}catch(e){msg('Remote-status kon nog niet worden gelezen: '+e.message,'warning')}finally{checking=false}}
  async function startPair(){const id=deviceId();if(!id)return msg('Verbind eerst de TV.','warning');const b=$('#secureRemoteStart');b.disabled=true;b.textContent='Control controleren…';try{const r=await api('/api/remote/pair/request',{method:'POST',body:JSON.stringify({deviceId:id})});if(r.paired||r.alreadyPaired){setPaired(true);return}if(r.pinRequired){$('#secureRemotePinBox').classList.remove('hidden');$('#secureRemotePin').focus();msg(r.message||'Kijk op de TV en vul de PIN in.','success')}}catch(e){msg('PIN aanvragen mislukt: '+e.message,'warning')}finally{b.disabled=false;b.textContent='Remote activeren'}}
  async function grant(){const id=deviceId(),pin=$('#secureRemotePin').value.trim();if(!id)return msg('Geen TV verbonden.','warning');if(!/^\d{4,8}$/.test(pin))return msg('Vul de PIN in die op de TV staat.','warning');const b=$('#secureRemoteGrant');b.disabled=true;b.textContent='Koppelen…';try{await api('/api/remote/pair/grant',{method:'POST',body:JSON.stringify({deviceId:id,pin})});setPaired(true);if(typeof toast==='function')toast('Remote secure gekoppeld en onthouden')}catch(e){msg('PIN koppelen mislukt: '+e.message,'warning')}finally{b.disabled=false;b.textContent='PIN bevestigen'}}
  async function switchHdmi1(){const id=deviceId();if(!id)return;if(!paired){msg('Activeer eerst Remote met de PIN van je TV.','warning');return}try{await api('/api/remote/hdmi1',{method:'POST',body:JSON.stringify({deviceId:id})});msg('TV staat nu op HDMI 1 • KPN ontvanger.','success');if(typeof toast==='function')toast('HDMI 1 • KPN TV')}catch(e){msg('HDMI 1 schakelen mislukt: '+e.message,'warning')}}
  async function sendKey(key){const id=deviceId();if(!id)return;if(!paired){msg('Activeer eerst Remote met de PIN van je TV.','warning');if(typeof toast==='function')toast('Ga naar Remote → Remote activeren');return}if(key==='WatchTV')return switchHdmi1();try{await api('/api/remote/key',{method:'POST',body:JSON.stringify({deviceId:id,key})});const n=$('#remoteNotice');if(n)n.classList.add('hidden')}catch(e){msg('Remote toets mislukt: '+e.message,'warning');if(/niet.*gekoppeld|credentials|401/i.test(e.message)){setPaired(false);check()}}}
  async function sendVolume(value){const id=deviceId();if(!id||!paired)return;try{const r=await api('/api/remote/volume',{method:'POST',body:JSON.stringify({deviceId:id,volume:Number(value)})});const x=$('#volumeValue');if(x)x.textContent=String(r.current)}catch(e){msg('Volume mislukt: '+e.message,'warning')}}
  async function toggleMute(){const id=deviceId();if(!id||!paired)return;try{const r=await api('/api/remote/mute',{method:'POST',body:JSON.stringify({deviceId:id})});lastMute=!!r.muted;const b=$('#muteBtn');if(b)b.textContent=lastMute?'Unmute':'Mute'}catch(e){msg('Mute mislukt: '+e.message,'warning')}}
  function bind(){
    $('#secureRemoteStart').addEventListener('click',startPair);$('#secureRemoteGrant').addEventListener('click',grant);$('#secureRemoteCancel').addEventListener('click',()=>$('#secureRemotePinBox').classList.add('hidden'));$('#secureRemotePin').addEventListener('keydown',e=>{if(e.key==='Enter')grant()});
    document.addEventListener('click',e=>{const k=e.target.closest('[data-key]');if(!k)return;e.preventDefault();e.stopImmediatePropagation();sendKey(k.dataset.key)},true);
    document.addEventListener('click',e=>{const b=e.target.closest('#muteBtn');if(!b)return;e.preventDefault();e.stopImmediatePropagation();if(!paired){msg('Activeer eerst Remote.','warning');return}toggleMute()},true);
    document.addEventListener('input',e=>{if(e.target?.id!=='volumeSlider')return;e.stopImmediatePropagation();if(!paired)return;clearTimeout(volumeTimer);volumeTimer=setTimeout(()=>sendVolume(e.target.value),140)},true);
    document.addEventListener('change',e=>{if(e.target?.id!=='volumeSlider')return;e.stopImmediatePropagation();if(paired)sendVolume(e.target.value)},true);
    setInterval(()=>{if(paired)syncButtons()},900);
  }
  function boot(){inject();let n=0;const t=setInterval(()=>{n++;if(!$('#secureRemoteCard'))inject();if(deviceId())check();if(n>25)clearInterval(t)},700)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();