const fs=require('fs');
const path=require('path');
const http=require('http');
const https=require('https');
const crypto=require('crypto');
const express=require('express');

const STORE=path.join(__dirname,'devices.local.json');
function readStore(){try{return JSON.parse(fs.readFileSync(STORE,'utf8'))}catch{return {devices:{}}}}
function resolveDevice(req){const ds=readStore().devices||{};const id=req.body?.deviceId||req.query?.deviceId;if(id&&ds[id])return ds[id];if(id){const hit=Object.values(ds).find(d=>d?.ip===id||`philips:${d?.ip}`===id);if(hit)return hit}const vals=Object.values(ds).filter(d=>d?.ip);if(vals.length===1)return vals[0];throw new Error('Geen TV gevonden. Verbind de TV eerst.')}
function parseJson(s){try{return s?JSON.parse(s):{}}catch{return {raw:s}}}
function plainRequest(protocol,ip,port,route,method='GET',body=null,headers={}){return new Promise((resolve,reject)=>{const data=body==null?null:Buffer.from(JSON.stringify(body));const mod=protocol==='https:'?https:http;const req=mod.request({hostname:ip,port,path:route,method,rejectUnauthorized:false,timeout:6500,headers:{Accept:'application/json',...(data?{'Content-Type':'application/json','Content-Length':data.length}:{}),...headers}},res=>{let text='';res.setEncoding('utf8');res.on('data',c=>text+=c);res.on('end',()=>resolve({status:res.statusCode||0,headers:res.headers,data:parseJson(text)}))});req.on('timeout',()=>req.destroy(new Error('TV request timed out')));req.on('error',reject);if(data)req.write(data);req.end()})}
function parseDigest(h=''){const s=String(Array.isArray(h)?h[0]:h).replace(/^Digest\s+/i,''),o={};const re=/(\w+)=(?:"([^"]*)"|([^,\s]+))/g;let m;while((m=re.exec(s)))o[m[1].toLowerCase()]=m[2]??m[3];return o}
function hash(alg,s){const a=String(alg||'MD5').toUpperCase(),n=a.startsWith('SHA-256')?'sha256':a.startsWith('SHA-512-256')?'sha512-256':'md5';return crypto.createHash(n).update(s).digest('hex')}
function authHeader(route,method,creds,challenge){const c=parseDigest(challenge);if(!c.realm||!c.nonce)throw new Error('Digest challenge ontbreekt');const alg=c.algorithm||'MD5',cnonce=crypto.randomBytes(8).toString('hex'),nc='00000001',qop=String(c.qop||'').split(',').map(x=>x.trim().replace(/^"|"$/g,'')).find(x=>x==='auth')||'';let ha1=hash(alg,`${creds.username}:${c.realm}:${creds.password}`);if(String(alg).toLowerCase().endsWith('-sess'))ha1=hash(alg,`${ha1}:${c.nonce}:${cnonce}`);const ha2=hash(alg,`${method}:${route}`),response=qop?hash(alg,`${ha1}:${c.nonce}:${nc}:${cnonce}:${qop}:${ha2}`):hash(alg,`${ha1}:${c.nonce}:${ha2}`),p=[`username="${creds.username}"`,`realm="${c.realm}"`,`nonce="${c.nonce}"`,`uri="${route}"`,`response="${response}"`];if(c.algorithm)p.push(`algorithm=${c.algorithm}`);if(c.opaque)p.push(`opaque="${c.opaque}"`);if(qop)p.push(`qop=${qop}`,`nc=${nc}`,`cnonce="${cnonce}"`);return `Digest ${p.join(', ')}`}
async function secureRequest(d,route,method='GET',body=null){if(!d.credentials)throw Object.assign(new Error('Secure TV credentials ontbreken.'),{code:'no_secure_credentials'});let probe=await plainRequest('https:',d.ip,1926,route,method,body);if(probe.status>=200&&probe.status<300)return probe.data;let challenge=probe.headers['www-authenticate'];if(probe.status!==401||!challenge){probe=await plainRequest('https:',d.ip,1926,'/6/system','GET');challenge=probe.headers['www-authenticate'];if(!challenge)throw new Error(`Secure endpoint gaf HTTP ${probe.status}`)}let r=await plainRequest('https:',d.ip,1926,route,method,body,{Authorization:authHeader(route,method,d.credentials,challenge)});if(r.status===401&&r.headers['www-authenticate'])r=await plainRequest('https:',d.ip,1926,route,method,body,{Authorization:authHeader(route,method,d.credentials,r.headers['www-authenticate'])});if(r.status<200||r.status>=300)throw Object.assign(new Error(r.data?.error_text||r.data?.error||`TV HTTP ${r.status}`),{status:r.status});return r.data}
async function tvGet(d,endpoint){for(const route of [`/6/${endpoint}`,`/1/${endpoint}`,`/${endpoint}`]){try{const r=await plainRequest('http:',d.ip,1925,route);if(r.status>=200&&r.status<300)return r.data;if(r.status!==404)break}catch{}}if(d.credentials)return secureRequest(d,`/6/${endpoint}`,'GET');throw new Error(`${endpoint} is niet via de huidige TV-verbinding beschikbaar.`)}
async function tvPost(d,endpoint,body){try{for(const route of [`/6/${endpoint}`,`/1/${endpoint}`,`/${endpoint}`]){const r=await plainRequest('http:',d.ip,1925,route,'POST',body);if(r.status>=200&&r.status<300)return r.data;if(![401,403,404].includes(r.status))throw new Error(`TV HTTP ${r.status}`)}}catch{}if(d.credentials)return secureRequest(d,`/6/${endpoint}`,'POST',body);throw new Error('Deze actie vereist de beveiligde TV-verbinding.')}
function packageFrom(x){return x?.intent?.component?.packageName||x?.component?.packageName||x?.packageName||x?.package||x?.id||null}
function appName(a,i){return a?.label||a?.name||a?.title||packageFrom(a)||`App ${i+1}`}
function normalizeApps(data){let list=data?.applications||data?.apps||data?.application||data;if(!Array.isArray(list)&&list&&typeof list==='object')list=Object.values(list);if(!Array.isArray(list))list=[];const seen=new Set(),out=[];list.forEach((a,i)=>{if(!a||typeof a!=='object')return;const pkg=packageFrom(a),id=String(a.id||pkg||i),key=pkg||id;if(seen.has(key))return;seen.add(key);out.push({id,name:appName(a,i),packageName:pkg,raw:a})});return out.sort((a,b)=>a.name.localeCompare(b.name,undefined,{sensitivity:'base'}))}
function activeInfo(activity){const pkg=activity?.intent?.component?.packageName||activity?.component?.packageName||activity?.packageName||null;const label=activity?.intent?.component?.className||activity?.component?.label||activity?.component?.source||activity?.channel?.name||null;return {packageName:pkg,label,raw:activity||null}}
async function sendKey(d,key){return tvPost(d,'input/key',{key})}
async function launchApp(d,app){const raw=app?.raw||app||{};let payload;if(raw.intent)payload=raw;else{const pkg=app?.packageName||app?.id;if(!pkg)throw new Error('Geen app package gevonden.');payload={intent:{component:{packageName:pkg}}}}return tvPost(d,'activities/launch',payload)}

const originalGet=express.application.get;
express.application.get=function(pathName,...handlers){if(pathName==='/api/apps')return originalGet.call(this,pathName,async(req,res)=>{try{const d=resolveDevice(req);const [appsR,actR]=await Promise.allSettled([tvGet(d,'applications'),tvGet(d,'activities/current')]);const activity=actR.status==='fulfilled'?activeInfo(actR.value):{packageName:null,label:null,raw:null};if(appsR.status!=='fulfilled')return res.json({apps:[],unavailable:true,reason:appsR.reason?.message||'App list unavailable',active:activity,securePossible:!!d.credentials});const apps=normalizeApps(appsR.value);for(const a of apps)a.active=!!(activity.packageName&&a.packageName===activity.packageName);res.json({apps,unavailable:false,active:activity,count:apps.length,secureUsed:!!d.credentials})}catch(e){res.status(400).json({error:e.message})}});return originalGet.call(this,pathName,...handlers)};
const originalPost=express.application.post;
express.application.post=function(pathName,...handlers){
 if(pathName==='/api/apps/launch')return originalPost.call(this,pathName,async(req,res)=>{try{const d=resolveDevice(req);await launchApp(d,req.body?.app||{});res.json({ok:true})}catch(e){res.status(400).json({error:e.message})}});
 if(pathName==='/api/apps/action')return originalPost.call(this,pathName,async(req,res)=>{try{const d=resolveDevice(req),action=String(req.body?.action||'').toLowerCase();if(action==='home'||action==='stop'){await sendKey(d,'Home');return res.json({ok:true,action:'home',note:'De huidige app is verlaten via Home.'})}if(action==='back'){await sendKey(d,'Back');return res.json({ok:true,action:'back'})}if(action==='reopen'){await launchApp(d,req.body?.app||{});return res.json({ok:true,action:'reopen'})}if(action==='refresh'){const a=await tvGet(d,'activities/current');return res.json({ok:true,action:'refresh',active:activeInfo(a)})}throw new Error('Onbekende app-actie.')}catch(e){res.status(400).json({error:e.message})}});
 return originalPost.call(this,pathName,...handlers)
};

console.log('[APPS] Installed-app discovery + active-app controls v2 ready');