const fs=require('fs');
const path=require('path');
const http=require('http');
const os=require('os');
const crypto=require('crypto');
const express=require('express');

const STORE=path.join(__dirname,'devices.local.json');
const pages=new Map();
let active=null;

function readStore(){try{return JSON.parse(fs.readFileSync(STORE,'utf8'))}catch{return {devices:{}}}}
function resolveTv(body={}){const ds=readStore().devices||{};if(body.ip)return body.ip;if(body.deviceId&&ds[body.deviceId]?.ip)return ds[body.deviceId].ip;const ids=Object.keys(ds);if(ids.length===1)return ds[ids[0]].ip;throw new Error('Geen TV IP gevonden voor countdown.');}
function clamp(n,min,max,def){n=Number(n);return Number.isFinite(n)?Math.max(min,Math.min(max,n)):def}
function color(v,def){v=String(v||def||'').trim();return /^#[0-9a-f]{6}([0-9a-f]{2})?$/i.test(v)?v:def}
function safe(v,max){return String(v||'').slice(0,max)}
function postJson(ip,endpoint,body={},timeout=4500){return new Promise((resolve,reject)=>{const data=Buffer.from(JSON.stringify(body));const req=http.request({hostname:ip,port:7979,path:endpoint,method:'POST',timeout,headers:{'Content-Type':'application/json','Content-Length':data.length}},res=>{let text='';res.setEncoding('utf8');res.on('data',c=>text+=c);res.on('end',()=>resolve({status:res.statusCode||0,text}))});req.on('timeout',()=>req.destroy(new Error('PiPup timeout')));req.on('error',reject);req.write(data);req.end()})}
function nativePosition(p){if(typeof p==='number')return clamp(p,0,4,4);const map={'top-right':0,'top-left':1,'bottom-right':2,'bottom-left':3,'center':4};return map[p]??4}
function bridgeIpFor(tvIp){const nets=os.networkInterfaces(),all=[];for(const list of Object.values(nets))for(const n of list||[])if(n.family==='IPv4'&&!n.internal)all.push(n.address);const prefix=String(tvIp||'').split('.').slice(0,3).join('.')+'.';return all.find(x=>x.startsWith(prefix))||all.find(x=>/^192\.168\.|^10\.|^172\.(1[6-9]|2\d|3[01])\./.test(x))||all[0]||'127.0.0.1'}
function format(ms,showDays=true){const total=Math.max(0,Math.ceil(ms/1000));const d=Math.floor(total/86400),h=Math.floor((total%86400)/3600),m=Math.floor((total%3600)/60),s=total%60,p=n=>String(n).padStart(2,'0');return showDays?`${String(d).padStart(2,'0')}:${p(h)}:${p(m)}:${p(s)}`:`${p(d*24+h)}:${p(m)}:${p(s)}`}
function rgbaHexToCss(v){const x=color(v,'#E6111820').slice(1);if(x.length===8){const a=parseInt(x.slice(0,2),16)/255;return `rgba(${parseInt(x.slice(2,4),16)},${parseInt(x.slice(4,6),16)},${parseInt(x.slice(6,8),16)},${a.toFixed(3)})`}return v}
function solidCss(v){const x=color(v,'#E6111820').slice(1);return x.length===8?`#${x.slice(2)}`:`#${x}`}
function renderPage(p){const d=JSON.stringify({durationMs:p.durationMs,title:p.title,label:p.label,titleColor:p.titleColor,messageColor:p.messageColor,bg:solidCss(p.backgroundColor),titleSize:p.titleSize,messageSize:p.messageSize,showDays:p.showDays}).replace(/</g,'\\u003c');return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no"><meta name="color-scheme" content="dark"><style>*{box-sizing:border-box}html,body{margin:0!important;padding:0!important;width:100%;height:100%;overflow:hidden;background:${solidCss(p.backgroundColor)}!important;font-family:Roboto,Arial,sans-serif;-webkit-text-size-adjust:none}.wrap{position:absolute;inset:0;width:100%;height:100%;margin:0;padding:0;background:${solidCss(p.backgroundColor)};display:flex;align-items:center;justify-content:center}.card{width:100%;height:100%;margin:0;padding:18px 24px;border:0;outline:0;border-radius:0;background:${solidCss(p.backgroundColor)};box-shadow:none;overflow:hidden;display:flex;flex-direction:column;justify-content:center}.title{font-size:${p.titleSize}px;font-weight:800;letter-spacing:.08em;line-height:1.05;color:${p.titleColor}}.label{margin-top:7px;font-size:${Math.max(12,Math.round(p.messageSize*.45))}px;line-height:1.15;color:${p.messageColor};opacity:.85}.time{margin-top:7px;font-size:${p.messageSize}px;font-weight:900;line-height:1;font-variant-numeric:tabular-nums;letter-spacing:.055em;white-space:nowrap;color:${p.messageColor}.bar{height:4px;margin-top:14px;border-radius:999px;background:rgba(255,255,255,.16);overflow:hidden}.bar>i{display:block;width:100%;height:100%;background:${p.messageColor};transform-origin:left center;animation:bar ${Math.max(1,p.durationMs/1000)}s linear forwards}@keyframes bar{to{transform:scaleX(0)}}</style></head><body><div class="wrap"><div class="card"><div class="title" id="t"></div><div class="label" id="l"></div><div class="time" id="v">--:--:--:--</div><div class="bar"><i></i></div></div></div><script>const d=${d};document.documentElement.style.background=d.bg;document.body.style.background=d.bg;document.getElementById('t').textContent=d.title;document.getElementById('l').textContent=d.label;const el=document.getElementById('v'),start=performance.now(),pad=n=>String(n).padStart(2,'0');function fmt(ms){const q=Math.max(0,Math.ceil(ms/1000)),D=Math.floor(q/86400),H=Math.floor(q%86400/3600),M=Math.floor(q%3600/60),S=q%60;return d.showDays?String(D).padStart(2,'0')+':'+pad(H)+':'+pad(M)+':'+pad(S):pad(D*24+H)+':'+pad(M)+':'+pad(S)}function tick(){const left=Math.max(0,d.durationMs-(performance.now()-start));el.textContent=fmt(left);if(left>0)requestAnimationFrame(tick)}tick();</script></body></html>`}
function installCountdownStatic(){const prev=express.static;express.static=function(root,options){const mw=prev(root,options);return function(req,res,next){const m=req.method==='GET'&&req.path.match(/^\/countdown-tv\/([a-f0-9]+)$/);if(m){const page=pages.get(m[1]);if(!page)return res.status(404).send('Countdown verlopen');res.set('Cache-Control','no-store, no-cache, must-revalidate');res.set('X-Content-Type-Options','nosniff');res.type('html').send(renderPage(page));return}mw(req,res,next)}}}
installCountdownStatic();
async function cancelPopup(ip){try{await postJson(ip,'/cancel',{})}catch{}}
function clearActiveTimers(a){if(!a)return;if(a.finishTimer)clearTimeout(a.finishTimer);if(a.token)pages.delete(a.token)}
async function showTimer(a,remainingMs){remainingMs=Math.max(0,Math.min(remainingMs,a.endAt?Math.max(0,a.endAt-Date.now()):remainingMs));const token=crypto.randomBytes(12).toString('hex');if(a.token)pages.delete(a.token);a.token=token;pages.set(token,{durationMs:remainingMs,title:a.title,label:a.label,titleColor:a.titleColor,messageColor:a.messageColor,backgroundColor:a.backgroundColor,titleSize:a.titleSize,messageSize:a.messageSize,showDays:a.showDays});const uri=`http://${bridgeIpFor(a.ip)}:8765/countdown-tv/${token}`;const duration=Math.max(2,Math.ceil(remainingMs/1000)+2);const payload={duration,position:a.position,backgroundColor:solidCss(a.backgroundColor),media:{web:{uri,width:720,height:180}}};const r=await postJson(a.ip,'/notify',payload);if(r.status<200||r.status>=300){pages.delete(token);throw new Error(`PiPup HTTP ${r.status}`)}a.lastError=null;a.mode='single-live-overlay-v3';return uri}
async function finishCountdown(a){if(active!==a)return;active=null;pages.delete(a.token);if(a.showFinished){try{await postJson(a.ip,'/notify',{duration:5,position:a.position,title:a.finishedTitle,titleColor:a.titleColor,titleSize:a.titleSize,message:a.finishedMessage,messageColor:a.messageColor,messageSize:Math.max(14,Math.round(a.messageSize*.55)),backgroundColor:a.backgroundColor})}catch{}}else await cancelPopup(a.ip)}
function scheduleFinish(a,remaining){if(a.finishTimer)clearTimeout(a.finishTimer);a.finishTimer=setTimeout(()=>finishCountdown(a),Math.max(0,remaining));a.finishTimer.unref?.()}
function snapshot(){if(!active)return {active:false};const remaining=active.paused?active.pausedRemaining:Math.max(0,active.endAt-Date.now());return {active:true,paused:active.paused,remainingMs:remaining,endAt:active.paused?null:active.endAt,ip:active.ip,position:active.position,title:active.title,label:active.label,lastError:active.lastError||null,display:format(remaining,active.showDays),mode:active.mode||'single-live-overlay-v3'}}
async function startCountdown(body){const ip=resolveTv(body),days=clamp(body.days,0,3650,0),hours=clamp(body.hours,0,23,0),minutes=clamp(body.minutes,0,59,0),seconds=clamp(body.seconds,0,59,0);const totalMs=((days*86400)+(hours*3600)+(minutes*60)+seconds)*1000;if(totalMs<1000)throw new Error('Countdown moet minimaal 1 seconde zijn.');if(active){const old=active;active=null;clearActiveTimers(old);await cancelPopup(old.ip)}const a={ip,totalMs,endAt:Date.now()+totalMs,paused:false,pausedRemaining:0,position:nativePosition(body.position),title:safe(body.title||'COUNTDOWN',80),label:safe(body.label||'',120),titleColor:color(body.titleColor,'#FFFFFF'),messageColor:color(body.messageColor,'#FFFFFF'),backgroundColor:color(body.backgroundColor,'#E6111820'),titleSize:clamp(body.titleSize,8,60,18),messageSize:clamp(body.messageSize,16,76,34),showDays:body.showDays!==false,showFinished:body.showFinished!==false,finishedTitle:safe(body.finishedTitle||'COUNTDOWN',80),finishedMessage:safe(body.finishedMessage||'Tijd is voorbij!',160),lastError:null,finishTimer:null,token:null,mode:'single-live-overlay-v3'};active=a;try{await showTimer(a,totalMs);scheduleFinish(a,Math.max(0,a.endAt-Date.now()))}catch(e){active=null;clearActiveTimers(a);throw e}return snapshot()}

const oldListen=express.application.listen;
express.application.listen=function(...args){if(!this.__countdownRoutes){this.__countdownRoutes=true;
 this.post('/api/countdown/start',async(req,res)=>{try{res.json({ok:true,...await startCountdown(req.body||{})})}catch(e){res.status(400).json({error:e.message,code:'countdown_start_failed'})}});
 this.get('/api/countdown/status',(req,res)=>res.json(snapshot()));
 this.post('/api/countdown/pause',async(req,res)=>{try{if(!active)return res.json({ok:true,active:false});if(!active.paused){active.pausedRemaining=Math.max(0,active.endAt-Date.now());active.paused=true;if(active.finishTimer)clearTimeout(active.finishTimer);pages.delete(active.token);active.token=null;await cancelPopup(active.ip)}res.json({ok:true,...snapshot()})}catch(e){res.status(500).json({error:e.message})}});
 this.post('/api/countdown/resume',async(req,res)=>{try{if(!active)return res.status(404).json({error:'Geen actieve countdown.'});if(active.paused){const remaining=active.pausedRemaining;const oldEnd=active.endAt;active.endAt=Date.now()+remaining;try{await showTimer(active,remaining);active.paused=false;scheduleFinish(active,Math.max(0,active.endAt-Date.now()))}catch(e){active.endAt=oldEnd;active.paused=true;throw e}}res.json({ok:true,...snapshot()})}catch(e){res.status(500).json({error:e.message})}});
 this.post('/api/countdown/stop',async(req,res)=>{try{if(active){const old=active;active=null;clearActiveTimers(old);await cancelPopup(old.ip)}else{try{await cancelPopup(resolveTv(req.body||{}))}catch{}}res.json({ok:true,active:false})}catch(e){res.status(500).json({error:e.message})}});
 }
 return oldListen.apply(this,args)};

console.log('[COUNTDOWN] Single-overlay PiPup countdown engine v3 ready - no transparent WebView frame');